! Forcheck interface to MPI-2
! Copyright Forcheck b.v., 2009

module mpi_constants

! Return codes
INTEGER, PARAMETER :: MPI_SUCCESS = 0
INTEGER, PARAMETER :: MPI_ERR_ACCESS = 1
INTEGER, PARAMETER :: MPI_ERR_AMODE = 2
INTEGER, PARAMETER :: MPI_ERR_ASSERT = 3
INTEGER, PARAMETER :: MPI_ERR_BAD_FILE = 4
INTEGER, PARAMETER :: MPI_ERR_BASE = 5
INTEGER, PARAMETER :: MPI_ERR_CONVERSION = 6
INTEGER, PARAMETER :: MPI_ERR_DISP = 7
INTEGER, PARAMETER :: MPI_ERR_DUP_DATAREP = 8
INTEGER, PARAMETER :: MPI_ERR_FILE_EXISTS = 9
INTEGER, PARAMETER :: MPI_ERR_FILE_IN_USE = 10
INTEGER, PARAMETER :: MPI_ERR_FILE = 11
INTEGER, PARAMETER :: MPI_ERR_INFO_KEY = 12
INTEGER, PARAMETER :: MPI_ERR_INFO_NOKEY = 13
INTEGER, PARAMETER :: MPI_ERR_INFO_VALUE = 14
INTEGER, PARAMETER :: MPI_ERR_INFO = 15
INTEGER, PARAMETER :: MPI_ERR_IO = 16
INTEGER, PARAMETER :: MPI_ERR_KEYVAL = 17
INTEGER, PARAMETER :: MPI_ERR_LOCKTYPE = 18
INTEGER, PARAMETER :: MPI_ERR_NAME = 19
INTEGER, PARAMETER :: MPI_ERR_NO_MEM = 20
INTEGER, PARAMETER :: MPI_ERR_NOT_SAME = 21
INTEGER, PARAMETER :: MPI_ERR_NO_SPACE = 22
INTEGER, PARAMETER :: MPI_ERR_NO_SUCH_FILE = 23
INTEGER, PARAMETER :: MPI_ERR_PORT = 24
INTEGER, PARAMETER :: MPI_ERR_QUOTA = 25
INTEGER, PARAMETER :: MPI_ERR_READ_ONLY = 26
INTEGER, PARAMETER :: MPI_ERR_RMA_CONFLICT = 27
INTEGER, PARAMETER :: MPI_ERR_RMA_SYNC = 28
INTEGER, PARAMETER :: MPI_ERR_SERVICE = 29
INTEGER, PARAMETER :: MPI_ERR_SIZE = 30
INTEGER, PARAMETER :: MPI_ERR_SPAWN = 31
INTEGER, PARAMETER :: MPI_ERR_UNSUPPORTED_DATAREP = 32
INTEGER, PARAMETER :: MPI_ERR_UNSUPPORTED_OPERATION = 33
INTEGER, PARAMETER :: MPI_ERR_WIN = 34

! Return status
integer, parameter :: MPI_SOURCE = 1
integer, parameter :: MPI_TAG    = 2
integer, parameter :: MPI_ERROR  = 3
integer, parameter :: MPI_STATUS_SIZE = 3

! Assorted Constants
INTEGER, PARAMETER :: MPI_IN_PLACE = 1
INTEGER, PARAMETER :: MPI_LOCK_EXCLUSIVE = 1
INTEGER, PARAMETER :: MPI_LOCK_SHARED = 1
INTEGER, PARAMETER :: MPI_ROOT = 1

! Variable Address Size (Fortran only)
INTEGER, PARAMETER :: MPI_ADDRESS_KIND = 4
INTEGER, PARAMETER :: MPI_INTEGER_KIND = 4
INTEGER, PARAMETER :: MPI_OFFSET_KIND = 4

! Maximum Sizes for Strings
INTEGER, PARAMETER :: MPI_MAX_DATAREP_STRING = 512
INTEGER, PARAMETER :: MPI_MAX_INFO_KEY = 512
INTEGER, PARAMETER :: MPI_MAX_INFO_VAL = 512
INTEGER, PARAMETER :: MPI_MAX_OBJECT_NAME = 512
INTEGER, PARAMETER :: MPI_MAX_PORT_NAME = 512

! Predefined Reduce Operations
Integer, Parameter :: MPI_LAND = 1
Integer, Parameter :: MPI_MAX  = 1
Integer, Parameter :: MPI_MIN  = 1
Integer, Parameter :: MPI_SUM  = 1

! Named Predefined Datatypes
INTEGER, PARAMETER :: MPI_WCHAR = 2

! C and C++ (no Fortran) Named Predefined Datatypes
INTEGER, PARAMETER :: MPI_Fint = 4

! Optional C and C++ (no Fortran) Named Predefined Datatypes
INTEGER, PARAMETER :: MPI_UNSIGNED_LONG_LONG = 8
INTEGER, PARAMETER :: MPI_SIGNED_CHAR = 1

! Predefined Attribute Keys
INTEGER, PARAMETER :: MPI_APPNUM = 1
INTEGER, PARAMETER :: MPI_LASTUSEDCODE = 1
INTEGER, PARAMETER :: MPI_UNIVERSE_SIZE = 1
INTEGER, PARAMETER :: MPI_WIN_BASE = 1
INTEGER, PARAMETER :: MPI_WIN_DISP_UNIT = 1
INTEGER, PARAMETER :: MPI_WIN_SIZE = 1

! Collective Operations
INTEGER, PARAMETER :: MPI_REPLACE = 1

! Null Handles
INTEGER, PARAMETER :: MPI_FILE_NULL = 0
INTEGER, PARAMETER :: MPI_INFO_NULL = 0
INTEGER, PARAMETER :: MPI_WIN_NULL = 0

! Mode Constants
INTEGER, PARAMETER :: MPI_MODE_APPEND = 1
INTEGER, PARAMETER :: MPI_MODE_CREATE = 2
INTEGER, PARAMETER :: MPI_MODE_DELETE_ON_CLOSE = 3
INTEGER, PARAMETER :: MPI_MODE_EXCL = 4
INTEGER, PARAMETER :: MPI_MODE_NOCHECK = 5
INTEGER, PARAMETER :: MPI_MODE_NOPRECEDE = 6
INTEGER, PARAMETER :: MPI_MODE_NOPUT = 7
INTEGER, PARAMETER :: MPI_MODE_NOSTORE = 8
INTEGER, PARAMETER :: MPI_MODE_NOSUCCEED = 9
INTEGER, PARAMETER :: MPI_MODE_RDONLY = 10
INTEGER, PARAMETER :: MPI_MODE_RDWR = 11
INTEGER, PARAMETER :: MPI_MODE_SEQUENTIAL = 12
INTEGER, PARAMETER :: MPI_MODE_UNIQUE_OPEN = 13
INTEGER, PARAMETER :: MPI_MODE_WRONLY = 14

! Datatype Decoding Constants
INTEGER, PARAMETER :: MPI_COMBINER_CONTIGUOUS = 1
INTEGER, PARAMETER :: MPI_COMBINER_DARRAY = 2
INTEGER, PARAMETER :: MPI_COMBINER_DUP = 3
INTEGER, PARAMETER :: MPI_COMBINER_F90_COMPLEX = 4
INTEGER, PARAMETER :: MPI_COMBINER_F90_INTEGER = 5
INTEGER, PARAMETER :: MPI_COMBINER_F90_REAL = 6
INTEGER, PARAMETER :: MPI_COMBINER_HINDEXED_INTEGER = 7
INTEGER, PARAMETER :: MPI_COMBINER_HINDEXED = 8
INTEGER, PARAMETER :: MPI_COMBINER_HVECTOR_INTEGER = 9
INTEGER, PARAMETER :: MPI_COMBINER_HVECTOR = 10
INTEGER, PARAMETER :: MPI_COMBINER_INDEXED_BLOCK = 11
INTEGER, PARAMETER :: MPI_COMBINER_INDEXED = 12
INTEGER, PARAMETER :: MPI_COMBINER_NAMED = 13
INTEGER, PARAMETER :: MPI_COMBINER_RESIZED = 14
INTEGER, PARAMETER :: MPI_COMBINER_STRUCT_INTEGER = 15
INTEGER, PARAMETER :: MPI_COMBINER_STRUCT = 16
INTEGER, PARAMETER :: MPI_COMBINER_SUBARRAY = 17
INTEGER, PARAMETER :: MPI_COMBINER_VECTOR = 18

! Threads Constants
INTEGER, PARAMETER :: MPI_THREAD_FUNNELED = 1
INTEGER, PARAMETER :: MPI_THREAD_MULTIPLE = 2
INTEGER, PARAMETER :: MPI_THREAD_SERIALIZED = 3
INTEGER, PARAMETER :: MPI_THREAD_SINGLE = 4

! File Operation Constants
INTEGER, PARAMETER :: MPI_DISPLACEMENT_CURRENT = 1
INTEGER, PARAMETER :: MPI_DISTRIBUTE_BLOCK = 2
INTEGER, PARAMETER :: MPI_DISTRIBUTE_CYCLIC = 3
INTEGER, PARAMETER :: MPI_DISTRIBUTE_DFLT_DARG = 4
INTEGER, PARAMETER :: MPI_DISTRIBUTE_NONE = 5
INTEGER, PARAMETER :: MPI_ORDER_C = 6
INTEGER, PARAMETER :: MPI_ORDER_FORTRAN = 7
INTEGER, PARAMETER :: MPI_SEEK_CUR = 8
INTEGER, PARAMETER :: MPI_SEEK_END = 9
INTEGER, PARAMETER :: MPI_SEEK_SET = 10

! F90 Datatype Matching Constants
INTEGER, PARAMETER :: MPI_TYPECLASS_COMPLEX = 1
INTEGER, PARAMETER :: MPI_TYPECLASS_INTEGER = 2
INTEGER, PARAMETER :: MPI_TYPECLASS_REAL = 3

! Handles to Assorted Structures in C and C++ (no Fortran)
INTEGER, PARAMETER :: MPI_File = 0
INTEGER, PARAMETER :: MPI_Info = 0
INTEGER, PARAMETER :: MPI_Win = 0

! Constants Specifying Empty or Ignored Input
INTEGER, PARAMETER :: MPI_ARGVS_NULL = 1
INTEGER, PARAMETER :: MPI_ARGV_NULL = 2
INTEGER, PARAMETER :: MPI_ERRCODES_IGNORE = 3
INTEGER, PARAMETER :: MPI_STATUSES_IGNORE = 4
INTEGER, PARAMETER :: MPI_STATUS_IGNORE = 5

! C Constants Specifying Ignored Input (no C++ or Fortran)
INTEGER, PARAMETER :: MPI_F_STATUSES_IGNORE = 0
INTEGER, PARAMETER :: MPI_F_STATUS_IGNORE = 0

! C and C++ cpp Constants and Fortran Parameters
INTEGER, PARAMETER :: MPI_SUBVERSION = 1
INTEGER, PARAMETER :: MPI_VERSION = 2

! GLOBAL

  Integer, Parameter :: MPI_UNDEFINED   = 0
  Integer, Parameter :: MPI_COMM_NULL   = 0
  Integer, Parameter :: MPI_COMM_WORLD  = 1

  Integer, Parameter :: MPI_ANY_SOURCE = 1
  Integer, Parameter :: MPI_ANY_TAG = 1
  Integer, Parameter :: MPI_BOTTOM = 1

! Datatypes
  Integer, Parameter :: MPI_INTEGER = 1
  Integer, Parameter :: MPI_REAL = 2
  Integer, Parameter :: MPI_DOUBLE_PRECISION = 3
  Integer, Parameter :: MPI_COMPLEX = 4
  Integer, Parameter :: MPI_LOGICAL = 6
  Integer, Parameter :: MPI_CHARACTER = 7

  Integer, Parameter :: MPI_DOUBLE_COMPLEX = 5
  Integer, Parameter :: MPI_INTEGER1 = 1
  Integer, Parameter :: MPI_INTEGER2 = 1
  Integer, Parameter :: MPI_INTEGER4 = 1
  Integer, Parameter :: MPI_INTEGER8 = 1
  Integer, Parameter :: MPI_INTEGER16 = 1
  Integer, Parameter :: MPI_REAL2 = 1
  Integer, Parameter :: MPI_REAL4 = 1
  Integer, Parameter :: MPI_REAL8 = 1
  Integer, Parameter :: MPI_REAL16 = 1
  Integer, Parameter :: MPI_COMPLEX4 = 1
  Integer, Parameter :: MPI_COMPLEX8 = 1
  Integer, Parameter :: MPI_COMPLEX16 = 1
  Integer, Parameter :: MPI_COMPLEX32 = 1

  Integer, Parameter :: MPI_2INTEGER = 1
  Integer, Parameter :: MPI_2REAL = 1
  Integer, Parameter :: MPI_2DOUBLE_PRECISION = 1
  Integer, Parameter :: MPI_2COMPLEX = 1
  Integer, Parameter :: MPI_2DOUBLE_COMPLEX = 1

  Integer, Parameter :: MPI_BYTE = 8
  Integer, Parameter :: MPI_PACKED = 9
  Integer, Parameter :: MPI_LB = 1
  Integer, Parameter :: MPI_UB = 2
end module

module mpi
use mpi_constants
interface

! MPI-1.1 Fortran Bindings

 SUBROUTINE MPI_ABORT(COMM, ERRORCODE, IERROR)
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: COMM, ERRORCODE
  INTEGER, INTENT(OUT) :: IERROR
 END SUBROUTINE
 SUBROUTINE MPI_ADDRESS(LOCATION[PLURI], ADDRESS, IERROR)
  IMPLICIT NONE
  CLASS(*) :: LOCATION(*)
  INTEGER, INTENT(OUT) :: ADDRESS, IERROR
 END SUBROUTINE
 SUBROUTINE MPI_ALLGATHER(SENDBUF[PLURI], SENDCOUNT[PLURI], SENDTYPE, RECVBUF, RECVCOUNT, RECVTYPE, COMM, IERROR)
  IMPLICIT NONE
  CLASS(*), INTENT(IN) :: SENDBUF(*)
  CLASS(*), INTENT(OUT) :: RECVBUF(*)
  INTEGER, INTENT(IN) :: SENDCOUNT, SENDTYPE, RECVCOUNT, RECVTYPE, COMM
  INTEGER, INTENT(OUT) :: IERROR
 END SUBROUTINE
 SUBROUTINE MPI_ALLGATHERV(SENDBUF[PLURI], SENDCOUNT, SENDTYPE, RECVBUF, RECVCOUNTS[PLURI],&
                           DISPLS[PLURI], RECVTYPE, COMM, IERROR)
  IMPLICIT NONE
  CLASS(*), INTENT(IN) :: SENDBUF(*)
  CLASS(*), INTENT(OUT) :: RECVBUF(*)
  INTEGER, INTENT(IN) :: SENDCOUNT, SENDTYPE, RECVCOUNTS(*), DISPLS(*), RECVTYPE, COMM
  INTEGER, INTENT(OUT) :: IERROR
 END SUBROUTINE
 SUBROUTINE MPI_ALLREDUCE(SENDBUF[PLURI], RECVBUF[PLURI], COUNT, DATATYPE, OP, COMM, IERROR)
  IMPLICIT NONE
  CLASS(*), INTENT(IN) :: SENDBUF(*)
  CLASS(*), INTENT(OUT) :: RECVBUF(*)
  INTEGER, INTENT(IN) :: COUNT, DATATYPE, OP, COMM
  INTEGER, INTENT(OUT) :: IERROR
 END SUBROUTINE
 SUBROUTINE MPI_ALLTOALL(SENDBUF[PLURI], SENDCOUNT, SENDTYPE, RECVBUF[PLURI], RECVCOUNT, RECVTYPE, &
                         COMM, IERROR)
  IMPLICIT NONE
  CLASS(*), INTENT(IN) :: SENDBUF(*)
  CLASS(*), INTENT(OUT) :: RECVBUF(*)
  INTEGER, INTENT(IN) :: SENDCOUNT, SENDTYPE, RECVCOUNT, RECVTYPE, COMM
  INTEGER, INTENT(OUT) :: IERROR
 END SUBROUTINE
 SUBROUTINE MPI_ALLTOALLV(SENDBUF[PLURI], SENDCOUNTS[PLURI], SDISPLS[PLURI], SENDTYPE, RECVBUF[PLURI], &
                          RECVCOUNTS[PLURI], RDISPLS[PLURI], RECVTYPE, COMM, IERROR)
  IMPLICIT NONE
  CLASS(*), INTENT(IN) :: SENDBUF(*)
  CLASS(*), INTENT(OUT) :: RECVBUF(*)
  INTEGER, INTENT(IN) :: SENDCOUNTS(*), SDISPLS(*), SENDTYPE, RECVCOUNTS(*), RDISPLS(*), RECVTYPE, &
                         COMM
  INTEGER, INTENT(OUT) :: IERROR
 END SUBROUTINE 
 SUBROUTINE MPI_ATTR_GET(COMM, KEYVAL, ATTRIBUTE_VAL, FLAG, IERROR)
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: COMM, KEYVAL
  INTEGER, INTENT(OUT) ::  ATTRIBUTE_VAL, IERROR
  LOGICAL, INTENT(OUT) :: FLAG
 END SUBROUTINE
 SUBROUTINE MPI_ATTR_DELETE(COMM, KEYVAL, IERROR)
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: COMM, KEYVAL
  INTEGER, INTENT(OUT) :: IERROR
 END SUBROUTINE
 SUBROUTINE MPI_ATTR_PUT(COMM, KEYVAL, ATTRIBUTE_VAL, IERROR)
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: COMM, KEYVAL, ATTRIBUTE_VAL
  INTEGER, INTENT(OUT) :: IERROR 
 END SUBROUTINE
 SUBROUTINE MPI_BARRIER(COMM, IERROR)
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: COMM
  INTEGER, INTENT(OUT) :: IERROR
 END SUBROUTINE
 SUBROUTINE MPI_BCAST(BUFFER[PLURI], COUNT, DATATYPE, ROOT, COMM, IERROR)
  IMPLICIT NONE
  CLASS(*), INTENT(INOUT) :: BUFFER(*)
  INTEGER, INTENT(IN) :: COUNT, DATATYPE, ROOT, COMM
  INTEGER, INTENT(OUT) :: IERROR
 END SUBROUTINE
 SUBROUTINE MPI_BSEND(BUF[PLURI], COUNT, DATATYPE, DEST, TAG, COMM, IERROR)
  IMPLICIT NONE
  CLASS(*), INTENT(IN) :: BUF(*)
  INTEGER, INTENT(IN) :: COUNT, DATATYPE, DEST, TAG, COMM
  INTEGER, INTENT(OUT) :: IERROR 
 END SUBROUTINE
 SUBROUTINE MPI_BSEND_INIT(BUF[PLURI], COUNT, DATATYPE, DEST, TAG, COMM, REQUEST, IERROR)
  IMPLICIT NONE
  CLASS(*), INTENT(IN) :: BUF(*)
  INTEGER, INTENT(IN) :: COUNT, DATATYPE, DEST, TAG, COMM, REQUEST
  INTEGER, INTENT(OUT) :: IERROR
 END SUBROUTINE
 SUBROUTINE MPI_BUFFER_ATTACH( BUFFER[PLURI], SIZE, IERROR)
  IMPLICIT NONE
  CLASS(*), INTENT(IN) :: BUFFER(*)
  INTEGER, INTENT(IN) :: SIZE
  INTEGER, INTENT(OUT) :: IERROR
 END SUBROUTINE
 SUBROUTINE MPI_BUFFER_DETACH( BUFFER_ADDR[PLURI], SIZE, IERROR)
  IMPLICIT NONE
  CLASS(*), INTENT(OUT) :: BUFFER_ADDR(*)
  INTEGER, INTENT(OUT) :: SIZE, IERROR
 END SUBROUTINE 
 SUBROUTINE MPI_CANCEL(REQUEST, IERROR)
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: REQUEST
  INTEGER, INTENT(OUT) :: IERROR
 END SUBROUTINE
 SUBROUTINE MPI_CART_COORDS(COMM, RANK, MAXDIMS, COORDS[PLURI], IERROR)
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: COMM, RANK, MAXDIMS
  INTEGER, INTENT(OUT) :: COORDS(*), IERROR
 END SUBROUTINE
 SUBROUTINE MPI_CART_CREATE(COMM_OLD, NDIMS, DIMS[PLURI], PERIODS[PLURI], REORDER, COMM_CART, IERROR)
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: COMM_OLD, NDIMS, DIMS(*)
  INTEGER, INTENT(OUT) :: COMM_CART, IERROR
  LOGICAL, INTENT(IN) :: PERIODS(*), REORDER
 END SUBROUTINE 
 SUBROUTINE MPI_CARTDIM_GET(COMM, NDIMS, IERROR)
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: COMM
  INTEGER, INTENT(OUT) :: NDIMS, IERROR
 END SUBROUTINE
 SUBROUTINE MPI_CART_GET(COMM, MAXDIMS, DIMS[PLURI], PERIODS[PLURI], COORDS[PLURI], IERROR)
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: COMM, MAXDIMS
  INTEGER, INTENT(OUT) :: DIMS(*), COORDS(*), IERROR
  LOGICAL, INTENT(OUT) :: PERIODS(*) 
 END SUBROUTINE
 SUBROUTINE MPI_CART_MAP(COMM, NDIMS, DIMS[PLURI], PERIODS[PLURI], NEWRANK, IERROR)
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: COMM, NDIMS, DIMS(*)
  INTEGER, INTENT(OUT) :: NEWRANK, IERROR
  LOGICAL, INTENT(IN) :: PERIODS(*)
 END SUBROUTINE
 SUBROUTINE MPI_CART_RANK(COMM, COORDS[PLURI], RANK, IERROR)
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: COMM, COORDS(*)
  INTEGER, INTENT(OUT) :: RANK, IERROR
 END SUBROUTINE
 SUBROUTINE MPI_CART_SHIFT(COMM, DIRECTION, DISP, RANK_SOURCE, RANK_DEST, IERROR)
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: COMM, DIRECTION, DISP
  INTEGER, INTENT(OUT) :: RANK_SOURCE, RANK_DEST, IERROR 
 END SUBROUTINE
 SUBROUTINE MPI_CART_SUB(COMM, REMAIN_DIMS[PLURI], NEWCOMM, IERROR)
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: COMM
  INTEGER, INTENT(OUT) :: NEWCOMM, IERROR
  LOGICAL, INTENT(IN) :: REMAIN_DIMS(*)
 END SUBROUTINE
 SUBROUTINE MPI_COMM_COMPARE(COMM1, COMM2, RESULT, IERROR)
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: COMM1, COMM2
  INTEGER, INTENT(OUT) :: RESULT, IERROR
 END SUBROUTINE 
 SUBROUTINE MPI_COMM_CREATE(COMM, GROUP, NEWCOMM, IERROR)
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: COMM, GROUP
  INTEGER, INTENT(OUT) :: NEWCOMM, IERROR
 END SUBROUTINE
 SUBROUTINE MPI_COMM_DUP(COMM, NEWCOMM, IERROR)
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: COMM
  INTEGER, INTENT(OUT) :: NEWCOMM, IERROR
 END SUBROUTINE
 SUBROUTINE MPI_COMM_FREE(COMM, IERROR)
  IMPLICIT NONE
  INTEGER, INTENT(INOUT) :: COMM
  INTEGER, INTENT(OUT) :: IERROR
 END SUBROUTINE
 SUBROUTINE MPI_COMM_GROUP(COMM, GROUP, IERROR)
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: COMM
  INTEGER, INTENT(OUT) :: GROUP, IERROR
 END SUBROUTINE
 SUBROUTINE MPI_COMM_RANK(COMM, RANK, IERROR)
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: COMM
  INTEGER, INTENT(OUT) :: RANK, IERROR
 END SUBROUTINE 
 SUBROUTINE MPI_COMM_REMOTE_GROUP(COMM, GROUP, IERROR)
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: COMM
  INTEGER, INTENT(OUT) :: GROUP, IERROR
 END SUBROUTINE
 SUBROUTINE MPI_COMM_REMOTE_SIZE(COMM, SIZE, IERROR)
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: COMM
  INTEGER, INTENT(OUT) :: SIZE, IERROR
 END SUBROUTINE
 SUBROUTINE MPI_COMM_SIZE(COMM, SIZE, IERROR)
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: COMM
  INTEGER, INTENT(OUT) :: SIZE, IERROR
 END SUBROUTINE
 SUBROUTINE MPI_COMM_SPLIT(COMM, COLOR, KEY, NEWCOMM, IERROR)
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: COMM, COLOR, KEY
  INTEGER, INTENT(OUT) :: NEWCOMM, IERROR
 END SUBROUTINE
 SUBROUTINE MPI_COMM_TEST_INTER(COMM, FLAG, IERROR)
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: COMM
  INTEGER, INTENT(OUT) :: IERROR
  LOGICAL, INTENT(OUT) :: FLAG
 END SUBROUTINE
 SUBROUTINE MPI_DIMS_CREATE(NNODES, NDIMS, DIMS[PLURI], IERROR)
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: NNODES, NDIMS
  INTEGER, INTENT(INOUT) :: DIMS(*)
  INTEGER, INTENT(OUT) :: IERROR
 END SUBROUTINE
 SUBROUTINE MPI_ERRHANDLER_CREATE(FUNCTION, ERRHANDLER, IERROR)
  IMPLICIT NONE
  EXTERNAL FUNCTION
  INTEGER, INTENT(OUT) :: ERRHANDLER, IERROR
 END SUBROUTINE
 SUBROUTINE MPI_ERRHANDLER_GET(COMM, ERRHANDLER, IERROR)
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: COMM
  INTEGER, INTENT(OUT) :: ERRHANDLER, IERROR
 END SUBROUTINE
 SUBROUTINE MPI_ERRHANDLER_FREE(ERRHANDLER, IERROR)
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: ERRHANDLER
  INTEGER, INTENT(OUT) :: IERROR
 END SUBROUTINE 
 SUBROUTINE MPI_ERRHANDLER_SET(COMM, ERRHANDLER, IERROR)
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: COMM, ERRHANDLER
  INTEGER, INTENT(OUT) :: IERROR
 END SUBROUTINE
 SUBROUTINE MPI_ERROR_CLASS(ERRORCODE, ERRORCLASS, IERROR)
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: ERRORCODE
  INTEGER, INTENT(OUT) :: ERRORCLASS, IERROR
 END SUBROUTINE
 SUBROUTINE MPI_ERROR_STRING(ERRORCODE, STRING, RESULTLEN, IERROR)
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: ERRORCODE
  INTEGER, INTENT(OUT) :: RESULTLEN, IERROR
  CHARACTER*(*), INTENT(OUT) :: STRING
 END SUBROUTINE
 SUBROUTINE MPI_FINALIZE(IERROR)
  IMPLICIT NONE
  INTEGER, INTENT(OUT) :: IERROR 
 END SUBROUTINE
 SUBROUTINE MPI_GATHER(SENDBUF[PLURI], SENDCOUNT, SENDTYPE, RECVBUF[PLURI], RECVCOUNT, RECVTYPE, ROOT, &
                       COMM, IERROR)
  IMPLICIT NONE
  CLASS(*), INTENT(IN) :: SENDBUF(*)
  CLASS(*), INTENT(OUT) :: RECVBUF(*)
  INTEGER, INTENT(IN) :: SENDCOUNT, SENDTYPE, RECVCOUNT, RECVTYPE, ROOT, COMM
  INTEGER, INTENT(OUT) :: IERROR
 END SUBROUTINE 
 SUBROUTINE MPI_GET_COUNT(STATUS, DATATYPE, COUNT, IERROR)
  IMPORT
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: STATUS(MPI_STATUS_SIZE), DATATYPE
  INTEGER, INTENT(OUT) :: COUNT, IERROR
 END SUBROUTINE
 SUBROUTINE MPI_GET_ELEMENTS(STATUS, DATATYPE, COUNT, IERROR)
  IMPORT
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: STATUS(MPI_STATUS_SIZE), DATATYPE
  INTEGER, INTENT(OUT) :: COUNT, IERROR
 END SUBROUTINE
 SUBROUTINE MPI_GET_PROCESSOR_NAME( NAME, RESULTLEN, IERROR)
  IMPLICIT NONE
  CHARACTER*(*), INTENT(OUT) :: NAME
  INTEGER, INTENT(OUT) :: RESULTLEN,IERROR
 END SUBROUTINE 
 SUBROUTINE GATHERV(SENDBUF[PLURI], SENDCOUNT, SENDTYPE, RECVBUF[PLURI], RECVCOUNTS[PLURI], DISPLS[PLURI], &
                    RECVTYPE, ROOT, COMM, IERROR)
  IMPLICIT NONE
  CLASS(*), INTENT(IN) :: SENDBUF(*)
  CLASS(*), INTENT(OUT) :: RECVBUF(*)
  INTEGER, INTENT(IN) :: SENDCOUNT, SENDTYPE, RECVCOUNTS(*), DISPLS(*), RECVTYPE, ROOT, COMM
  INTEGER, INTENT(OUT) :: IERROR
 END SUBROUTINE
 SUBROUTINE MPI_GRAPH_CREATE(COMM_OLD, NNODES, INDEX[PLURI], EDGES[PLURI], REORDER, COMM_GRAPH, IERROR)
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: COMM_OLD, NNODES, INDEX(*), EDGES(*)
  INTEGER, INTENT(OUT) :: COMM_GRAPH, IERROR
  LOGICAL, INTENT(IN) :: REORDER 
 END SUBROUTINE
 SUBROUTINE MPI_GRAPHDIMS_GET(COMM, NNODES, NEDGES, IERROR)
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: COMM
  INTEGER, INTENT(OUT) :: NNODES, NEDGES, IERROR
 END SUBROUTINE
 SUBROUTINE MPI_GRAPH_GET(COMM, MAXINDEX, MAXEDGES, INDEX[PLURI], EDGES[PLURI], IERROR)
  IMPLICIT NONE
  INTEGER COMM, MAXINDEX, MAXEDGES
  INTEGER, INTENT(OUT) :: INDEX(*), EDGES(*), IERROR
 END SUBROUTINE 
 SUBROUTINE MPI_GRAPH_MAP(COMM, NNODES, INDEX[PLURI], EDGES[PLURI], NEWRANK, IERROR)
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: COMM, NNODES, INDEX(*), EDGES(*)
  INTEGER, INTENT(OUT) :: NEWRANK, IERROR 
 END SUBROUTINE
 SUBROUTINE MPI_GRAPH_NEIGHBORS(COMM, RANK, MAXNEIGHBORS, NEIGHBORS, IERROR)
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: COMM, RANK, MAXNEIGHBORS[PLURI]
  INTEGER, INTENT(OUT) :: NEIGHBORS(*), IERROR
 END SUBROUTINE
 SUBROUTINE MPI_GRAPH_NEIGHBORS_COUNT(COMM, RANK, NNEIGHBORS, IERROR)
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: COMM, RANK
  INTEGER, INTENT(OUT) :: NNEIGHBORS, IERROR
 END SUBROUTINE
 SUBROUTINE MPI_GROUP_COMPARE(GROUP1, GROUP2, RESULT, IERROR)
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: GROUP1, GROUP2
  INTEGER, INTENT(OUT) :: RESULT, IERROR
 END SUBROUTINE
 SUBROUTINE MPI_GROUP_DIFFERENCE(GROUP1, GROUP2, NEWGROUP, IERROR)
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: GROUP1, GROUP2
  INTEGER, INTENT(OUT) :: NEWGROUP, IERROR
 END SUBROUTINE 
 SUBROUTINE MPI_GROUP_EXCL(GROUP, N, RANKS[PLURI], NEWGROUP, IERROR)
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: GROUP, N, RANKS(*)
  INTEGER, INTENT(OUT) :: NEWGROUP, IERROR
 END SUBROUTINE
 SUBROUTINE MPI_GROUP_FREE(GROUP, IERROR)
  IMPLICIT NONE
  INTEGER, INTENT(INOUT) :: GROUP
  INTEGER, INTENT(OUT) :: IERROR 
 END SUBROUTINE
 SUBROUTINE MPI_GROUP_INCL(GROUP, N, RANKS[PLURI], NEWGROUP, IERROR)
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: GROUP, N, RANKS(*)
  INTEGER, INTENT(OUT) :: NEWGROUP, IERROR
 END SUBROUTINE
 SUBROUTINE MPI_GROUP_INTERSECTION(GROUP1, GROUP2, NEWGROUP, IERROR)
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: GROUP1, GROUP2
  INTEGER, INTENT(OUT) :: NEWGROUP, IERROR
 END SUBROUTINE
 SUBROUTINE MPI_GROUP_RANGE_EXCL(GROUP, N, RANGES[PLURI], NEWGROUP, IERROR)
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: GROUP, N, RANGES(3,*)
  INTEGER, INTENT(OUT) :: NEWGROUP, IERROR
 END SUBROUTINE
 SUBROUTINE MPI_GROUP_RANGE_INCL(GROUP, N, RANGES[PLURI], NEWGROUP, IERROR)
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: GROUP, N, RANGES(3,*)
  INTEGER, INTENT(OUT) :: NEWGROUP, IERROR 
 END SUBROUTINE
 SUBROUTINE MPI_GROUP_RANK(GROUP, RANK, IERROR)
  IMPLICIT NONE
  INTEGER, INTENT(IN) ::  GROUP
  INTEGER, INTENT(OUT) :: RANK, IERROR
 END SUBROUTINE
 SUBROUTINE MPI_GROUP_SIZE(GROUP, SIZE, IERROR)
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: GROUP
  INTEGER, INTENT(OUT) :: SIZE, IERROR
 END SUBROUTINE
 SUBROUTINE MPI_GROUP_TRANSLATE_RANKS(GROUP1, N, RANKS1[PLURI], GROUP2, RANKS2[PLURI], IERROR)
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: GROUP1, N, RANKS1(*), GROUP2
  INTEGER, INTENT(OUT) :: RANKS2(*), IERROR
 END SUBROUTINE
 SUBROUTINE MPI_GROUP_UNION(GROUP1, GROUP2, NEWGROUP, IERROR)
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: GROUP1, GROUP2
  INTEGER, INTENT(OUT) :: NEWGROUP, IERROR
 END SUBROUTINE 
 SUBROUTINE MPI_IBSEND(BUF[PLURI], COUNT, DATATYPE, DEST, TAG, COMM, REQUEST, IERROR)
  IMPLICIT NONE
  CLASS(*), INTENT(IN) ::  BUF(*)
  INTEGER, INTENT(IN) :: COUNT, DATATYPE, DEST, TAG, COMM
  INTEGER, INTENT(OUT) :: REQUEST, IERROR
 END SUBROUTINE
 SUBROUTINE MPI_INIT(IERROR)
  IMPLICIT NONE
  INTEGER, INTENT(OUT) :: IERROR
 END SUBROUTINE
 SUBROUTINE MPI_INITIALIZED(FLAG, IERROR)
  IMPLICIT NONE
  LOGICAL, INTENT(OUT) :: FLAG
  INTEGER, INTENT(OUT) :: IERROR
 END SUBROUTINE
 SUBROUTINE MPI_INTERCOMM_CREATE(LOCAL_COMM, LOCAL_LEADER, PEER_COMM, REMOTE_LEADER, TAG, NEWINTERCOMM,&
                                 IERROR)
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: LOCAL_COMM, LOCAL_LEADER, PEER_COMM, REMOTE_LEADER, TAG
  INTEGER, INTENT(OUT) :: NEWINTERCOMM, IERROR
 END SUBROUTINE
 SUBROUTINE MPI_INTERCOMM_MERGE(INTERCOMM, HIGH, NEWINTRACOMM, IERROR)
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: INTERCOMM
  INTEGER, INTENT(OUT) :: NEWINTRACOMM, IERROR
  LOGICAL, INTENT(IN) :: HIGH
 END SUBROUTINE
 SUBROUTINE MPI_IPROBE(SOURCE, TAG, COMM, FLAG, STATUS, IERROR)
  IMPORT
  IMPLICIT NONE
  LOGICAL, INTENT(OUT) :: FLAG
  INTEGER SOURCE, TAG, COMM
  INTEGER, INTENT(OUT) :: STATUS(MPI_STATUS_SIZE), IERROR
 END SUBROUTINE
 SUBROUTINE MPI_IRECV(BUF[PLURI], COUNT, DATATYPE, SOURCE, TAG, COMM, REQUEST, IERROR)
  IMPLICIT NONE
  CLASS(*), INTENT(OUT) :: BUF(*)
  INTEGER, INTENT(IN) :: COUNT, DATATYPE, SOURCE, TAG, COMM
  INTEGER, INTENT(OUT) :: REQUEST, IERROR
 END SUBROUTINE
 SUBROUTINE MPI_IRSEND(BUF[PLURI], COUNT, DATATYPE, DEST, TAG, COMM, REQUEST, IERROR)
  IMPLICIT NONE
  CLASS(*), INTENT(IN) :: BUF(*)
  INTEGER, INTENT(IN) :: COUNT, DATATYPE, DEST, TAG, COMM
  INTEGER, INTENT(OUT) :: REQUEST, IERROR
 END SUBROUTINE
 SUBROUTINE MPI_ISEND(BUF[PLURI], COUNT, DATATYPE, DEST, TAG, COMM, REQUEST, IERROR)
  IMPLICIT NONE
  CLASS(*), INTENT(IN) :: BUF(*)
  INTEGER, INTENT(IN) :: COUNT, DATATYPE, DEST, TAG, COMM
  INTEGER, INTENT(OUT) :: REQUEST, IERROR
 END SUBROUTINE
 SUBROUTINE MPI_ISSEND(BUF[PLURI], COUNT, DATATYPE, DEST, TAG, COMM, REQUEST, IERROR)
  IMPLICIT NONE
  CLASS(*), INTENT(IN) :: BUF(*)
  INTEGER, INTENT(IN) :: COUNT, DATATYPE, DEST, TAG, COMM
  INTEGER, INTENT(OUT) :: REQUEST, IERROR
 END SUBROUTINE
 SUBROUTINE MPI_KEYVAL_CREATE(COPY_FN, DELETE_FN, KEYVAL, EXTRA_STATE, IERROR)
  IMPLICIT NONE
  EXTERNAL COPY_FN, DELETE_FN
  INTEGER, INTENT(IN) :: KEYVAL, EXTRA_STATE
  INTEGER, INTENT(OUT) :: IERROR
 END SUBROUTINE
 SUBROUTINE MPI_KEYVAL_FREE(KEYVAL, IERROR)
  IMPLICIT NONE
  INTEGER, INTENT(INOUT) :: KEYVAL
  INTEGER, INTENT(OUT) :: IERROR 
 END SUBROUTINE
 SUBROUTINE MPI_OP_CREATE( FUNCTION, COMMUTE, OP, IERROR)
  IMPLICIT NONE
  EXTERNAL FUNCTION
  LOGICAL, INTENT(IN) :: COMMUTE
  INTEGER, INTENT(OUT) :: OP, IERROR
 END SUBROUTINE
 SUBROUTINE MPI_OP_FREE( OP, IERROR)
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: OP
  INTEGER, INTENT(OUT) :: IERROR
 END SUBROUTINE
 SUBROUTINE MPI_PACK(INBUF[PLURI], INCOUNT, DATATYPE, OUTBUF[PLURI], OUTSIZE, POSITION, COMM, IERROR)
  IMPLICIT NONE
  CLASS(*), INTENT(IN) :: INBUF(*)
  CLASS(*), INTENT(OUT) :: OUTBUF(*)
  INTEGER, INTENT(IN) :: INCOUNT, DATATYPE, OUTSIZE, COMM
  INTEGER, INTENT(INOUT) :: POSITION
  INTEGER, INTENT(OUT) :: IERROR
 END SUBROUTINE
 SUBROUTINE MPI_PACK_SIZE(INCOUNT, DATATYPE, COMM, SIZE, IERROR)
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: INCOUNT, DATATYPE, COMM
  INTEGER, INTENT(OUT) :: SIZE, IERROR
 END SUBROUTINE
 SUBROUTINE MPI_PROBE(SOURCE, TAG, COMM, STATUS, IERROR)
  IMPORT
  IMPLICIT NONE
  INTEGER SOURCE, TAG, COMM
  INTEGER, INTENT(OUT) :: STATUS(MPI_STATUS_SIZE), IERROR
 END SUBROUTINE 
 SUBROUTINE MPI_RECV(BUF[PLURI], COUNT, DATATYPE, SOURCE, TAG, COMM, STATUS, IERROR)
  IMPORT
  IMPLICIT NONE
  CLASS(*), INTENT(OUT) :: BUF(*)
  INTEGER, INTENT(IN) :: COUNT, DATATYPE, SOURCE, TAG, COMM
  INTEGER, INTENT(OUT) :: STATUS(MPI_STATUS_SIZE), IERROR
 END SUBROUTINE 
 SUBROUTINE MPI_RECV_INIT(BUF[PLURI], COUNT, DATATYPE, SOURCE, TAG, COMM, REQUEST, IERROR)
  IMPLICIT NONE
  CLASS(*), INTENT(OUT) :: BUF(*)
  INTEGER, INTENT(IN) :: COUNT, DATATYPE, SOURCE, TAG, COMM
  INTEGER, INTENT(OUT) :: REQUEST, IERROR
 END SUBROUTINE
 SUBROUTINE MPI_REDUCE(SENDBUF[PLURI], RECVBUF[PLURI], COUNT, DATATYPE, OP, ROOT, COMM, IERROR)
  IMPLICIT NONE
  CLASS(*), INTENT(IN) :: SENDBUF(*)
  CLASS(*), INTENT(OUT) :: RECVBUF(*)
  INTEGER, INTENT(IN) :: COUNT, DATATYPE, OP, ROOT, COMM
  INTEGER, INTENT(OUT) :: IERROR
 END SUBROUTINE
 SUBROUTINE MPI_REDUCE_SCATTER(SENDBUF[PLURI], RECVBUF[PLURI], RECVCOUNTS[PLURI], DATATYPE, OP, COMM, &
                               IERROR)
  IMPLICIT NONE
  CLASS(*), INTENT(IN) :: SENDBUF(*)
  CLASS(*), INTENT(OUT) :: RECVBUF(*)
  INTEGER, INTENT(IN) :: RECVCOUNTS(*), DATATYPE, OP, COMM
  INTEGER, INTENT(OUT) :: IERROR
 END SUBROUTINE
 SUBROUTINE MPI_REQUEST_FREE(REQUEST, IERROR)
  IMPLICIT NONE
  INTEGER, INTENT(INOUT) :: REQUEST
  INTEGER, INTENT(OUT) :: IERROR
 END SUBROUTINE
 SUBROUTINE MPI_RSEND(BUF[PLURI], COUNT, DATATYPE, DEST, TAG, COMM, IERROR)
  IMPLICIT NONE
  CLASS(*), INTENT(IN) :: BUF(*)
  INTEGER, INTENT(IN) :: COUNT, DATATYPE, DEST, TAG, COMM
  INTEGER, INTENT(OUT) :: IERROR 
 END SUBROUTINE
 SUBROUTINE MPI_RSEND_INIT(BUF[PLURI], COUNT, DATATYPE, DEST, TAG, COMM, REQUEST, IERROR)
  IMPLICIT NONE
  CLASS(*), INTENT(IN) :: BUF(*)
  INTEGER, INTENT(IN) :: COUNT, DATATYPE, DEST, TAG, COMM, REQUEST
  INTEGER, INTENT(OUT) :: IERROR
 END SUBROUTINE
 SUBROUTINE MPI_SCAN(SENDBUF[PLURI], RECVBUF[PLURI], COUNT, DATATYPE, OP, COMM, IERROR)
  IMPLICIT NONE
  CLASS(*), INTENT(IN) :: SENDBUF(*)
  CLASS(*), INTENT(OUT) :: RECVBUF(*)
  INTEGER, INTENT(IN) :: COUNT, DATATYPE, OP, COMM
  INTEGER, INTENT(OUT) :: IERROR
 END SUBROUTINE
 SUBROUTINE MPI_SCATTER(SENDBUF[PLURI], SENDCOUNT, SENDTYPE, RECVBUF[PLURI], RECVCOUNT, RECVTYPE, ROOT,&
                        COMM, IERROR)
  IMPLICIT NONE
  CLASS(*), INTENT(IN) :: SENDBUF(*)
  CLASS(*), INTENT(OUT) :: RECVBUF(*)
  INTEGER, INTENT(IN) :: SENDCOUNT, SENDTYPE, RECVCOUNT, RECVTYPE, ROOT, COMM
  INTEGER, INTENT(OUT) :: IERROR
 END SUBROUTINE
 SUBROUTINE MPI_SCATTERV(SENDBUF[PLURI], SENDCOUNTS[PLURI], DISPLS[PLURI], SENDTYPE, RECVBUF[PLURI], &
                         RECVCOUNT, RECVTYPE, ROOT, COMM, IERROR)
  IMPLICIT NONE
  CLASS(*), INTENT(IN) :: SENDBUF(*)
  CLASS(*), INTENT(OUT) :: RECVBUF(*)
  INTEGER, INTENT(IN) :: SENDCOUNTS(*), DISPLS(*), SENDTYPE, RECVCOUNT, RECVTYPE, ROOT, COMM
  INTEGER, INTENT(OUT) :: IERROR
 END SUBROUTINE
 SUBROUTINE MPI_SEND(BUF[PLURI], COUNT, DATATYPE, DEST, TAG, COMM, IERROR)
  IMPLICIT NONE
  CLASS(*), INTENT(IN) :: BUF(*)
  INTEGER, INTENT(IN) :: COUNT, DATATYPE, DEST, TAG, COMM
  INTEGER, INTENT(OUT) :: IERROR
 END SUBROUTINE
 SUBROUTINE MPI_SENDRECV(SENDBUF[PLURI], SENDCOUNT, SENDTYPE, DEST, SENDTAG, RECVBUF[PLURI], RECVCOUNT, &
                         RECVTYPE, SOURCE, RECVTAG, COMM, STATUS, IERROR)
  IMPORT
  IMPLICIT NONE
  CLASS(*), INTENT(IN) :: SENDBUF(*)
  CLASS(*), INTENT(OUT) :: RECVBUF(*)
  INTEGER, INTENT(IN) :: SENDCOUNT, SENDTYPE, DEST, SENDTAG, RECVCOUNT, RECVTYPE, SOURCE, RECVTAG, COMM
  INTEGER, INTENT(OUT) :: STATUS(MPI_STATUS_SIZE), IERROR
 END SUBROUTINE
 SUBROUTINE MPI_SENDRECV_REPLACE(BUF[PLURI], COUNT, DATATYPE, DEST, SENDTAG, SOURCE, RECVTAG, COMM, &
                                 STATUS, IERROR)
  IMPORT
  IMPLICIT NONE
  CLASS(*), INTENT(INOUT) :: BUF(*)
  INTEGER, INTENT(IN) :: COUNT, DATATYPE, DEST, SENDTAG, SOURCE, RECVTAG, COMM
  INTEGER, INTENT(OUT) :: STATUS(MPI_STATUS_SIZE), IERROR 
 END SUBROUTINE
 SUBROUTINE MPI_SEND_INIT(BUF[PLURI], COUNT, DATATYPE, DEST, TAG, COMM, REQUEST, IERROR)
  IMPLICIT NONE
  CLASS(*), INTENT(IN) :: BUF(*)
  INTEGER, INTENT(IN) :: COUNT, DATATYPE, DEST, TAG, COMM, REQUEST
  INTEGER, INTENT(OUT) :: IERROR
 END SUBROUTINE
 SUBROUTINE MPI_SSEND(BUF[PLURI], COUNT, DATATYPE, DEST, TAG, COMM, IERROR)
  IMPLICIT NONE
  CLASS(*), INTENT(IN) :: BUF(*)
  INTEGER, INTENT(IN) :: COUNT, DATATYPE, DEST, TAG, COMM
  INTEGER, INTENT(OUT) :: IERROR
 END SUBROUTINE 
 SUBROUTINE MPI_SSEND_INIT(BUF[PLURI], COUNT, DATATYPE, DEST, TAG, COMM, REQUEST, IERROR)
  IMPLICIT NONE
  CLASS(*), INTENT(IN) :: BUF(*)
  INTEGER, INTENT(IN) :: COUNT, DATATYPE, DEST, TAG, COMM, REQUEST
  INTEGER, INTENT(OUT) :: IERROR 
 END SUBROUTINE
 SUBROUTINE MPI_START(REQUEST, IERROR)
  IMPLICIT NONE
  INTEGER, INTENT(INOUT) :: REQUEST
  INTEGER, INTENT(OUT) :: IERROR 
 END SUBROUTINE
 SUBROUTINE MPI_STARTALL(COUNT, ARRAY_OF_REQUESTS[PLURI], IERROR)
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: COUNT
  INTEGER, INTENT(INOUT) :: ARRAY_OF_REQUESTS(*)
  INTEGER, INTENT(OUT) :: IERROR
 END SUBROUTINE
 SUBROUTINE MPI_TEST(REQUEST, FLAG, STATUS, IERROR)
  IMPORT
  IMPLICIT NONE
  LOGICAL, INTENT(OUT) :: FLAG
  INTEGER, INTENT(INOUT) :: REQUEST
  INTEGER, INTENT(OUT) :: STATUS(MPI_STATUS_SIZE), IERROR
 END SUBROUTINE
 SUBROUTINE MPI_TESTALL(COUNT, ARRAY_OF_REQUESTS[PLURI], FLAG, ARRAY_OF_STATUSES[PLURI], IERROR)
  IMPORT
  IMPLICIT NONE
  LOGICAL, INTENT(OUT) :: FLAG
  INTEGER, INTENT(IN) :: COUNT
  INTEGER, INTENT(INOUT) :: ARRAY_OF_REQUESTS(*)
  INTEGER, INTENT(OUT) :: ARRAY_OF_STATUSES(MPI_STATUS_SIZE,*), IERROR
 END SUBROUTINE
 SUBROUTINE MPI_TESTANY(COUNT, ARRAY_OF_REQUESTS[PLURI], INDEX, FLAG, STATUS, IERROR)
  IMPORT
  IMPLICIT NONE
  LOGICAL, INTENT(OUT) :: FLAG
  INTEGER, INTENT(IN) :: COUNT
  INTEGER, INTENT(INOUT) :: ARRAY_OF_REQUESTS(*)
  INTEGER, INTENT(OUT) :: INDEX, STATUS(MPI_STATUS_SIZE), IERROR
 END SUBROUTINE
 SUBROUTINE MPI_TEST_CANCELLED(STATUS, FLAG, IERROR)
  IMPORT
  IMPLICIT NONE
  LOGICAL, INTENT(OUT) :: FLAG
  INTEGER, INTENT(IN) :: STATUS(MPI_STATUS_SIZE)
  INTEGER, INTENT(OUT) :: IERROR 
 END SUBROUTINE
 SUBROUTINE MPI_TESTSOME(INCOUNT, ARRAY_OF_REQUESTS[PLURI], OUTCOUNT, ARRAY_OF_INDICES[PLURI], &
                         ARRAY_OF_STATUSES[PLURI], IERROR)
  IMPORT
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: INCOUNT
  INTEGER, INTENT(INOUT) :: ARRAY_OF_REQUESTS(*)
  INTEGER, INTENT(OUT) :: OUTCOUNT, ARRAY_OF_INDICES(*), ARRAY_OF_STATUSES(MPI_STATUS_SIZE,*), IERROR
 END SUBROUTINE
 SUBROUTINE MPI_TOPO_TEST(COMM, STATUS, IERROR)
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: COMM
  INTEGER, INTENT(OUT) :: STATUS, IERROR
 END SUBROUTINE
 SUBROUTINE MPI_TYPE_COMMIT(DATATYPE, IERROR)
  IMPLICIT NONE
  INTEGER, INTENT(INOUT) :: DATATYPE
  INTEGER, INTENT(OUT) :: IERROR
 END SUBROUTINE
 SUBROUTINE MPI_TYPE_CONTIGUOUS(COUNT, OLDTYPE, NEWTYPE, IERROR)
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: COUNT, OLDTYPE
  INTEGER, INTENT(OUT) :: NEWTYPE, IERROR
 END SUBROUTINE
 SUBROUTINE MPI_TYPE_EXTENT(DATATYPE, EXTENT, IERROR)
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: DATATYPE
  INTEGER, INTENT(OUT) :: EXTENT, IERROR
 END SUBROUTINE
 SUBROUTINE MPI_TYPE_FREE(DATATYPE, IERROR)
  IMPLICIT NONE
  INTEGER, INTENT(INOUT) :: DATATYPE
  INTEGER, INTENT(OUT) :: IERROR 
 END SUBROUTINE
 SUBROUTINE MPI_TYPE_HINDEXED(COUNT, ARRAY_OF_BLOCKLENGTHS[PLURI], ARRAY_OF_DISPLACEMENTS[PLURI], &
                              OLDTYPE, NEWTYPE, IERROR)
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: COUNT, ARRAY_OF_BLOCKLENGTHS(*), ARRAY_OF_DISPLACEMENTS(*), OLDTYPE
  INTEGER, INTENT(OUT) :: NEWTYPE, IERROR
 END SUBROUTINE
 SUBROUTINE MPI_TYPE_HVECTOR(COUNT, BLOCKLENGTH, STRIDE, OLDTYPE, NEWTYPE, IERROR)
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: COUNT, BLOCKLENGTH, STRIDE, OLDTYPE
  INTEGER, INTENT(OUT) :: NEWTYPE, IERROR
 END SUBROUTINE
 SUBROUTINE MPI_TYPE_INDEXED(COUNT, ARRAY_OF_BLOCKLENGTHS[PLURI], ARRAY_OF_DISPLACEMENTS[PLURI], &
                             OLDTYPE, NEWTYPE, IERROR)
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: COUNT, ARRAY_OF_BLOCKLENGTHS(*), ARRAY_OF_DISPLACEMENTS(*), OLDTYPE
  INTEGER, INTENT(OUT) :: NEWTYPE, IERROR
 END SUBROUTINE
 SUBROUTINE MPI_TYPE_LB( DATATYPE, DISPLACEMENT, IERROR)
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: DATATYPE
  INTEGER, INTENT(OUT) :: DISPLACEMENT, IERROR
 END SUBROUTINE
 SUBROUTINE MPI_TYPE_SIZE(DATATYPE, SIZE, IERROR)
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: DATATYPE
  INTEGER, INTENT(OUT) :: SIZE, IERROR
 END SUBROUTINE
 SUBROUTINE MPI_TYPE_STRUCT(COUNT, ARRAY_OF_BLOCKLENGTHS[PLURI], ARRAY_OF_DISPLACEMENTS[PLURI], &
                            ARRAY_OF_TYPES[PLURI], NEWTYPE, IERROR)
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: COUNT, ARRAY_OF_BLOCKLENGTHS(*), ARRAY_OF_DISPLACEMENTS(*), ARRAY_OF_TYPES(*)
  INTEGER, INTENT(OUT) :: NEWTYPE, IERROR
 END SUBROUTINE
 SUBROUTINE MPI_TYPE_UB( DATATYPE, DISPLACEMENT, IERROR)
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: DATATYPE
  INTEGER, INTENT(OUT) :: DISPLACEMENT, IERROR
 END SUBROUTINE
 SUBROUTINE MPI_TYPE_VECTOR(COUNT, BLOCKLENGTH, STRIDE, OLDTYPE, NEWTYPE, IERROR)
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: COUNT, BLOCKLENGTH, STRIDE, OLDTYPE
  INTEGER, INTENT(OUT) :: NEWTYPE, IERROR
 END SUBROUTINE
 SUBROUTINE MPI_UNPACK(INBUF[PLURI], INSIZE, POSITION, OUTBUF[PLURI], OUTCOUNT, DATATYPE, COMM, IERROR)
  IMPLICIT NONE
  CLASS(*), INTENT(IN) :: INBUF(*)
  CLASS(*), INTENT(OUT) :: OUTBUF(*)
  INTEGER, INTENT(IN) :: INSIZE, OUTCOUNT, DATATYPE, COMM
  INTEGER, INTENT(INOUT) :: POSITION
  INTEGER, INTENT(OUT) :: IERROR
 END SUBROUTINE
 SUBROUTINE MPI_WAIT(REQUEST, STATUS, IERROR)
  IMPORT
  IMPLICIT NONE
  INTEGER, INTENT(INOUT) :: REQUEST
  INTEGER, INTENT(OUT) :: STATUS(MPI_STATUS_SIZE), IERROR
 END SUBROUTINE
 SUBROUTINE MPI_WAITALL(COUNT, ARRAY_OF_REQUESTS[PLURI], ARRAY_OF_STATUSES[PLURI], IERROR)
  IMPORT
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: COUNT
  INTEGER, INTENT(INOUT) :: ARRAY_OF_REQUESTS(*)
  INTEGER, INTENT(OUT) :: ARRAY_OF_STATUSES(MPI_STATUS_SIZE,*), IERROR
 END SUBROUTINE
 SUBROUTINE MPI_WAITANY(COUNT, ARRAY_OF_REQUESTS[PLURI], INDEX, STATUS, IERROR)
  IMPORT
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: COUNT
  INTEGER, INTENT(INOUT) :: ARRAY_OF_REQUESTS(*)
  INTEGER, INTENT(OUT) :: INDEX, STATUS(MPI_STATUS_SIZE), IERROR
 END SUBROUTINE
 SUBROUTINE MPI_WAITSOME(INCOUNT, ARRAY_OF_REQUESTS[PLURI], OUTCOUNT, ARRAY_OF_INDICES[PLURI], &
                         ARRAY_OF_STATUSES[PLURI], IERROR)
  IMPORT
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: INCOUNT
  INTEGER, INTENT(INOUT) :: ARRAY_OF_REQUESTS(*)
  INTEGER, INTENT(OUT) :: OUTCOUNT, ARRAY_OF_INDICES(*), ARRAY_OF_STATUSES(MPI_STATUS_SIZE,*), IERROR
 END SUBROUTINE
 DOUBLE PRECISION FUNCTION MPI_WTIME()
  IMPLICIT NONE
 END FUNCTION
 DOUBLE PRECISION FUNCTION MPI_WTICK()
  IMPLICIT NONE
 END FUNCTION

! MPI-1.2 Fortran Bindings

 SUBROUTINE MPI_GET_VERSION(VERSION, SUBVERSION, IERROR)
  IMPLICIT NONE
  INTEGER, INTENT(OUT) :: VERSION, SUBVERSION, IERROR
 END SUBROUTINE

! MPI-2 Fortran Bindings

 SUBROUTINE MPI_ACCUMULATE(ORIGIN_ADDR[PLURI], ORIGIN_COUNT, ORIGIN_DATATYPE, TARGET_RANK, TARGET_DISP,&
                           TARGET_COUNT, TARGET_DATATYPE, OP, WIN, IERROR)
  IMPORT
  IMPLICIT NONE
  CLASS(*), INTENT(IN) :: ORIGIN_ADDR(*)
  INTEGER(KIND=MPI_ADDRESS_KIND), INTENT(IN) :: TARGET_DISP
  INTEGER, INTENT(IN) :: ORIGIN_COUNT, ORIGIN_DATATYPE,TARGET_RANK, TARGET_COUNT, TARGET_DATATYPE,&
                         OP, WIN
  INTEGER, INTENT(OUT) :: IERROR
 END SUBROUTINE
 SUBROUTINE MPI_ADD_ERROR_CLASS(ERRORCLASS, IERROR)
  IMPLICIT NONE
  INTEGER, INTENT(OUT) :: ERRORCLASS, IERROR
 END SUBROUTINE
 SUBROUTINE MPI_ADD_ERROR_CODE(ERRORCLASS, ERRORCODE, IERROR)
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: ERRORCLASS
  INTEGER, INTENT(OUT) :: ERRORCODE, IERROR
 END SUBROUTINE
 SUBROUTINE MPI_ADD_ERROR_STRING(ERRORCODE, STRING, IERROR)
  INTEGER, INTENT(IN) :: ERRORCODE
  INTEGER, INTENT(OUT) :: IERROR
  CHARACTER*(*), INTENT(IN) :: STRING
 END SUBROUTINE
 SUBROUTINE MPI_ALLOC_MEM(SIZE, INFO, BASEPTR, IERROR)
  IMPORT
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: INFO
  INTEGER, INTENT(OUT) :: IERROR
  INTEGER(KIND=MPI_ADDRESS_KIND), INTENT(IN) :: SIZE
  INTEGER(KIND=MPI_ADDRESS_KIND), INTENT(OUT) :: BASEPTR
 END SUBROUTINE
 SUBROUTINE MPI_ALLTOALLW(SENDBUF[PLURI], SENDCOUNTS[PLURI], SDISPLS[PLURI], SENDTYPES[PLURI], &
                          RECVBUF[PLURI], RECVCOUNTS[PLURI], RDISPLS[PLURI], RECVTYPES[PLURI], COMM, IERROR)
  IMPLICIT NONE
  CLASS(*), INTENT(IN) :: SENDBUF(*)
  CLASS(*), INTENT(OUT) :: RECVBUF(*)
  INTEGER, INTENT(IN) :: SENDCOUNTS(*), SDISPLS(*), SENDTYPES(*), RECVCOUNTS(*), RDISPLS(*),&
                         RECVTYPES(*), COMM
  INTEGER, INTENT(OUT) :: IERROR
 END SUBROUTINE
 SUBROUTINE MPI_COMM_CALL_ERRHANDLER(COMM, ERRORCODE, IERROR)
  INTEGER, INTENT(IN) :: COMM, ERRORCODE
  INTEGER, INTENT(OUT) :: IERROR
 END SUBROUTINE
 SUBROUTINE MPI_COMM_CREATE_ERRHANDLER(FUNCTION, ERRHANDLER, IERROR)
  IMPLICIT NONE
  EXTERNAL FUNCTION
  INTEGER, INTENT(OUT) :: ERRHANDLER, IERROR
 END SUBROUTINE
 SUBROUTINE MPI_COMM_GET_ERRHANDLER(COMM, ERRHANDLER, IERROR)
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: COMM
  INTEGER, INTENT(OUT) :: ERRHANDLER, IERROR
 END SUBROUTINE
 SUBROUTINE MPI_COMM_SET_ERRHANDLER(COMM, ERRHANDLER, IERROR)
  IMPLICIT NONE
  INTEGER, INTENT(INOUT) :: COMM
  INTEGER, INTENT(IN) :: ERRHANDLER
  INTEGER, INTENT(OUT) :: IERROR
 END SUBROUTINE
 SUBROUTINE MPI_FINALIZED(FLAG, IERROR)
  IMPLICIT NONE
  LOGICAL, INTENT(OUT) :: FLAG
  INTEGER, INTENT(OUT) :: IERROR
 END SUBROUTINE
 SUBROUTINE MPI_FREE_MEM(BASE[PLURI], IERROR)
  IMPLICIT NONE
  CLASS(*) :: BASE(*)
  INTEGER, INTENT(OUT) :: IERROR
 END SUBROUTINE
 SUBROUTINE MPI_GET_ADDRESS(LOCATION[PLURI], ADDRESS, IERROR)
  IMPORT
  IMPLICIT NONE
  CLASS(*) :: LOCATION(*)
  INTEGER, INTENT(OUT) :: IERROR
  INTEGER(KIND=MPI_ADDRESS_KIND), INTENT(OUT) :: ADDRESS
 END SUBROUTINE
 SUBROUTINE MPI_INFO_CREATE(INFO, IERROR)
  IMPLICIT NONE
  INTEGER, INTENT(OUT) :: INFO, IERROR
 END SUBROUTINE
 SUBROUTINE MPI_INFO_DELETE(INFO, KEY, IERROR)
  IMPLICIT NONE
  INTEGER, INTENT(INOUT) :: INFO
  INTEGER, INTENT(OUT) :: IERROR
  CHARACTER*(*), INTENT(IN) :: KEY
 END SUBROUTINE
 SUBROUTINE MPI_INFO_DUP(INFO, NEWINFO, IERROR)
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: INFO
  INTEGER, INTENT(OUT) :: NEWINFO, IERROR
 END SUBROUTINE
 SUBROUTINE MPI_INFO_FREE(INFO, IERROR)
  IMPLICIT NONE
  INTEGER, INTENT(INOUT) :: INFO
  INTEGER, INTENT(OUT) :: IERROR
 END SUBROUTINE
 SUBROUTINE MPI_INFO_GET(INFO, KEY, VALUELEN, VALUE, FLAG, IERROR)
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: INFO, VALUELEN
  INTEGER, INTENT(OUT) :: IERROR
  CHARACTER*(*), INTENT(IN) :: KEY
  CHARACTER*(*), INTENT(OUT) :: VALUE
  LOGICAL, INTENT(OUT) :: FLAG
 END SUBROUTINE
 SUBROUTINE MPI_INFO_GET_NKEYS(INFO, NKEYS, IERROR)
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: INFO
  INTEGER, INTENT(OUT) :: NKEYS, IERROR
 END SUBROUTINE
 SUBROUTINE MPI_INFO_GET_NTHKEY(INFO, N, KEY, IERROR)
  INTEGER, INTENT(IN) :: INFO, N
  INTEGER, INTENT(OUT) :: IERROR
  CHARACTER*(*), INTENT(OUT) :: KEY
 END SUBROUTINE
 SUBROUTINE MPI_INFO_GET_VALUELEN(INFO, KEY, VALUELEN, FLAG, IERROR)
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: INFO
  INTEGER, INTENT(OUT) :: VALUELEN, IERROR
  LOGICAL, INTENT(OUT) :: FLAG
  CHARACTER*(*), INTENT(IN) :: KEY
 END SUBROUTINE
 SUBROUTINE MPI_INFO_SET(INFO, KEY, VALUE, IERROR)
  IMPLICIT NONE
  INTEGER, INTENT(INOUT) :: INFO
  INTEGER, INTENT(OUT) :: IERROR
  CHARACTER*(*), INTENT(IN) :: KEY, VALUE
 END SUBROUTINE
 SUBROUTINE MPI_PACK_EXTERNAL(DATAREP, INBUF[PLURI], INCOUNT, DATATYPE, OUTBUF[PLURI], OUTSIZE, &
                              POSITION, IERROR)
  IMPORT
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: INCOUNT, DATATYPE
  INTEGER, INTENT(OUT) :: IERROR
  INTEGER(KIND=MPI_ADDRESS_KIND), INTENT(IN) :: OUTSIZE
  INTEGER(KIND=MPI_ADDRESS_KIND), INTENT(INOUT) :: POSITION
  CHARACTER*(*), INTENT(IN) :: DATAREP
  CLASS(*), INTENT(IN) :: INBUF(*)
  CLASS(*), INTENT(OUT) :: OUTBUF(*)
 END SUBROUTINE
 SUBROUTINE MPI_PACK_EXTERNAL_SIZE(DATAREP, INCOUNT, DATATYPE, SIZE, IERROR)
  IMPORT
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: INCOUNT, DATATYPE
  INTEGER, INTENT(OUT) :: IERROR
  INTEGER(KIND=MPI_ADDRESS_KIND), INTENT(OUT) :: SIZE
  CHARACTER*(*), INTENT(IN) :: DATAREP
 END SUBROUTINE
 SUBROUTINE MPI_REQUEST_GET_STATUS( REQUEST, FLAG, STATUS, IERROR)
  IMPORT
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: REQUEST
  INTEGER, INTENT(OUT) :: STATUS(MPI_STATUS_SIZE), IERROR
  LOGICAL, INTENT(OUT) :: FLAG
 END SUBROUTINE
 SUBROUTINE MPI_TYPE_CREATE_DARRAY(SIZE, RANK, NDIMS, ARRAY_OF_GSIZES[PLURI], ARRAY_OF_DISTRIBS[PLURI], &
                                   ARRAY_OF_DARGS[PLURI], ARRAY_OF_PSIZES[PLURI], ORDER, OLDTYPE, &
                                   NEWTYPE, IERROR)
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: SIZE, RANK, NDIMS, ARRAY_OF_GSIZES(*), ARRAY_OF_DISTRIBS(*),&
                         ARRAY_OF_DARGS(*), ARRAY_OF_PSIZES(*), ORDER, OLDTYPE
  INTEGER, INTENT(OUT) :: NEWTYPE, IERROR
 END SUBROUTINE
 SUBROUTINE MPI_TYPE_CREATE_HINDEXED(COUNT, ARRAY_OF_BLOCKLENGTHS[PLURI], ARRAY_OF_DISPLACEMENTS[PLURI], &
                                     OLDTYPE, NEWTYPE, IERROR)
  IMPORT
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: COUNT, ARRAY_OF_BLOCKLENGTHS(*), OLDTYPE
  INTEGER, INTENT(OUT) :: NEWTYPE, IERROR
  INTEGER(KIND=MPI_ADDRESS_KIND), INTENT(IN) :: ARRAY_OF_DISPLACEMENTS(*)
 END SUBROUTINE
 SUBROUTINE MPI_TYPE_CREATE_HVECTOR(COUNT, BLOCKLENGTH, STRIDE, OLDTYPE, NEWTYPE, IERROR)
  IMPORT
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: COUNT, BLOCKLENGTH, OLDTYPE
  INTEGER, INTENT(OUT) :: NEWTYPE, IERROR
  INTEGER(KIND=MPI_ADDRESS_KIND), INTENT(IN) :: STRIDE
 END SUBROUTINE
 SUBROUTINE MPI_TYPE_CREATE_INDEXED_BLOCK(COUNT, BLOCKLENGTH, ARRAY_OF_DISPLACEMENTS[PLURI], OLDTYPE, &
                                          NEWTYPE, IERROR)
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: COUNT, BLOCKLENGTH, ARRAY_OF_DISPLACEMENTS(*), OLDTYPE
  INTEGER, INTENT(OUT) :: NEWTYPE, IERROR
 END SUBROUTINE
 SUBROUTINE MPI_TYPE_CREATE_RESIZED(OLDTYPE, LB, EXTENT, NEWTYPE, IERROR)
  IMPORT
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: OLDTYPE
  INTEGER, INTENT(OUT) :: NEWTYPE, IERROR
  INTEGER(KIND=MPI_ADDRESS_KIND), INTENT(IN) :: LB, EXTENT
 END SUBROUTINE
 SUBROUTINE MPI_TYPE_CREATE_STRUCT(COUNT, ARRAY_OF_BLOCKLENGTHS[PLURI], ARRAY_OF_DISPLACEMENTS[PLURI], &
                                   ARRAY_OF_TYPES[PLURI], NEWTYPE, IERROR)
  IMPORT
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: COUNT, ARRAY_OF_BLOCKLENGTHS(*), ARRAY_OF_TYPES(*)
  INTEGER, INTENT(OUT) :: NEWTYPE, IERROR
  INTEGER(KIND=MPI_ADDRESS_KIND), INTENT(IN) :: ARRAY_OF_DISPLACEMENTS(*)
 END SUBROUTINE
 SUBROUTINE MPI_TYPE_CREATE_SUBARRAY(NDIMS, ARRAY_OF_SIZES[PLURI], ARRAY_OF_SUBSIZES[PLURI], &
                                     ARRAY_OF_STARTS[PLURI], ORDER, OLDTYPE, NEWTYPE, IERROR)
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: NDIMS, ARRAY_OF_SIZES(*), ARRAY_OF_SUBSIZES(*), ARRAY_OF_STARTS(*), ORDER, &
                         OLDTYPE
  INTEGER, INTENT(OUT) :: NEWTYPE, IERROR
 END SUBROUTINE
 SUBROUTINE MPI_TYPE_GET_EXTENT(DATATYPE, LB, EXTENT, IERROR)
  IMPORT
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: DATATYPE
  INTEGER, INTENT(OUT) :: IERROR
  INTEGER(KIND = MPI_ADDRESS_KIND), INTENT(OUT) :: LB, EXTENT
 END SUBROUTINE
 SUBROUTINE MPI_TYPE_GET_TRUE_EXTENT(DATATYPE, TRUE_LB, TRUE_EXTENT, IERROR)
  IMPORT
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: DATATYPE
  INTEGER, INTENT(OUT) :: IERROR
  INTEGER(KIND = MPI_ADDRESS_KIND), INTENT(OUT) :: TRUE_LB, TRUE_EXTENT
 END SUBROUTINE
 SUBROUTINE MPI_UNPACK_EXTERNAL(DATAREP, INBUF[PLURI], INSIZE, POSITION, OUTBUF[PLURI], OUTCOUNT, &
                                DATATYPE, IERROR)
  IMPORT
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: OUTCOUNT, DATATYPE
  INTEGER, INTENT(OUT) :: IERROR
  INTEGER(KIND=MPI_ADDRESS_KIND), INTENT(IN) :: INSIZE
  INTEGER(KIND=MPI_ADDRESS_KIND), INTENT(INOUT) :: POSITION
  CHARACTER*(*), INTENT(IN) :: DATAREP
  CLASS(*), INTENT(IN) :: INBUF(*)
  CLASS(*), INTENT(OUT) :: OUTBUF(*)
 END SUBROUTINE
 SUBROUTINE MPI_WIN_CALL_ERRHANDLER(WIN, ERRORCODE, IERROR)
  INTEGER, INTENT(IN) :: WIN, ERRORCODE
  INTEGER, INTENT(OUT) :: IERROR
 END SUBROUTINE
 SUBROUTINE MPI_WIN_CREATE_ERRHANDLER(FUNCTION, ERRHANDLER, IERROR)
  IMPLICIT NONE
  EXTERNAL FUNCTION
  INTEGER, INTENT(OUT) :: ERRHANDLER, IERROR
 END SUBROUTINE
 SUBROUTINE MPI_WIN_GET_ERRHANDLER(WIN, ERRHANDLER, IERROR)
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: WIN
  INTEGER, INTENT(OUT) :: ERRHANDLER, IERROR
 END SUBROUTINE
 SUBROUTINE MPI_WIN_SET_ERRHANDLER(WIN, ERRHANDLER, IERROR)
  IMPLICIT NONE
  INTEGER, INTENT(INOUT) :: WIN
  INTEGER, INTENT(IN) :: ERRHANDLER
  INTEGER, INTENT(OUT) :: IERROR
 END SUBROUTINE

! Process Creation and Management

 SUBROUTINE MPI_CLOSE_PORT(PORT_NAME, IERROR)
  IMPLICIT NONE
  CHARACTER*(*), INTENT(IN) :: PORT_NAME
  INTEGER, INTENT(OUT) :: IERROR
 END SUBROUTINE
 SUBROUTINE MPI_COMM_ACCEPT(PORT_NAME, INFO, ROOT, COMM, NEWCOMM, IERROR)
  IMPLICIT NONE
  CHARACTER*(*), INTENT(IN) :: PORT_NAME
  INTEGER, INTENT(IN) :: INFO, ROOT, COMM
  INTEGER, INTENT(OUT) :: NEWCOMM, IERROR
 END SUBROUTINE
 SUBROUTINE MPI_COMM_CONNECT(PORT_NAME, INFO, ROOT, COMM, NEWCOMM, IERROR)
  IMPLICIT NONE
  CHARACTER*(*), INTENT(IN) :: PORT_NAME
  INTEGER, INTENT(IN) :: INFO, ROOT, COMM
  INTEGER, INTENT(OUT) :: NEWCOMM, IERROR
 END SUBROUTINE
 SUBROUTINE MPI_COMM_DISCONNECT(COMM, IERROR)
  IMPLICIT NONE
  INTEGER, INTENT(INOUT) :: COMM
  INTEGER, INTENT(OUT) :: IERROR
 END SUBROUTINE
 SUBROUTINE MPI_COMM_GET_PARENT(PARENT, IERROR)
  IMPLICIT NONE
  INTEGER, INTENT(OUT) :: PARENT, IERROR
 END SUBROUTINE
 SUBROUTINE MPI_COMM_JOIN(FD, INTERCOMM, IERROR)
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: FD
  INTEGER, INTENT(OUT) :: INTERCOMM, IERROR
 END SUBROUTINE
 SUBROUTINE MPI_COMM_SPAWN(COMMAND, ARGV, MAXPROCS, INFO, ROOT, COMM, INTERCOMM, ARRAY_OF_ERRCODES[PLURI], &
                           IERROR)
  IMPLICIT NONE
  CHARACTER*(*), INTENT(IN) :: COMMAND, ARGV(*)
  INTEGER, INTENT(IN) :: INFO, MAXPROCS, ROOT, COMM
  INTEGER, INTENT(OUT) :: INTERCOMM, ARRAY_OF_ERRCODES(*), IERROR
 END SUBROUTINE
 SUBROUTINE MPI_COMM_SPAWN_MULTIPLE(COUNT, ARRAY_OF_COMMANDS, ARRAY_OF_ARGV[PLURI], ARRAY_OF_MAXPROCS[PLURI], &
                                    ARRAY_OF_INFO[PLURI], ROOT, COMM, INTERCOMM, ARRAY_OF_ERRCODES[PLURI], &
                                    IERROR)
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: COUNT, ARRAY_OF_INFO(*), ARRAY_OF_MAXPROCS(*), ROOT, COMM
  INTEGER, INTENT(OUT) :: INTERCOMM, ARRAY_OF_ERRCODES(*), IERROR
  CHARACTER*(*), INTENT(IN) :: ARRAY_OF_COMMANDS(*), ARRAY_OF_ARGV(COUNT, *)
 END SUBROUTINE
 SUBROUTINE MPI_LOOKUP_NAME(SERVICE_NAME, INFO, PORT_NAME, IERROR)
  IMPLICIT NONE
  CHARACTER*(*), INTENT(IN) :: SERVICE_NAME
  CHARACTER*(*), INTENT(OUT) :: PORT_NAME
  INTEGER, INTENT(IN) :: INFO
  INTEGER, INTENT(OUT) :: IERROR
 END SUBROUTINE
 SUBROUTINE MPI_OPEN_PORT(INFO, PORT_NAME, IERROR)
  IMPLICIT NONE
  CHARACTER*(*), INTENT(OUT) :: PORT_NAME
  INTEGER, INTENT(IN) :: INFO
  INTEGER, INTENT(OUT) :: IERROR
 END SUBROUTINE
 SUBROUTINE MPI_PUBLISH_NAME(SERVICE_NAME, INFO, PORT_NAME, IERROR)
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: INFO
  INTEGER, INTENT(OUT) :: IERROR
  CHARACTER*(*), INTENT(IN) :: SERVICE_NAME, PORT_NAME
 END SUBROUTINE
 SUBROUTINE MPI_UNPUBLISH_NAME(SERVICE_NAME, INFO, PORT_NAME, IERROR)
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: INFO
  INTEGER, INTENT(OUT) :: IERROR
  CHARACTER*(*), INTENT(IN) :: SERVICE_NAME, PORT_NAME
 END SUBROUTINE

! One-Sided COmmunications

 SUBROUTINE MPI_GET(ORIGIN_ADDR[PLURI], ORIGIN_COUNT, ORIGIN_DATATYPE, TARGET_RANK, TARGET_DISP, &
                    TARGET_COUNT, TARGET_DATATYPE, WIN, IERROR)
  IMPORT
  IMPLICIT NONE
  CLASS(*), INTENT(OUT) :: ORIGIN_ADDR(*)
  INTEGER(KIND=MPI_ADDRESS_KIND) TARGET_DISP
  INTEGER ORIGIN_COUNT, ORIGIN_DATATYPE, TARGET_RANK, TARGET_COUNT, TARGET_DATATYPE, WIN, IERROR
 END SUBROUTINE
 SUBROUTINE MPI_PUT(ORIGIN_ADDR[PLURI], ORIGIN_COUNT, ORIGIN_DATATYPE, TARGET_RANK, TARGET_DISP, &
                    TARGET_COUNT, TARGET_DATATYPE, WIN, IERROR)
  IMPORT
  IMPLICIT NONE
  CLASS(*), INTENT(IN) :: ORIGIN_ADDR(*)
  INTEGER(KIND=MPI_ADDRESS_KIND) TARGET_DISP
  INTEGER, INTENT(IN) :: ORIGIN_COUNT, ORIGIN_DATATYPE, TARGET_RANK, TARGET_COUNT, TARGET_DATATYPE, &
                         WIN
  INTEGER, INTENT(OUT) :: IERROR
 END SUBROUTINE
 SUBROUTINE MPI_WIN_COMPLETE(WIN, IERROR)
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: WIN
  INTEGER, INTENT(OUT) :: IERROR
 END SUBROUTINE
 SUBROUTINE MPI_WIN_CREATE(BASE[PLURI], SIZE, DISP_UNIT, INFO, COMM, WIN, IERROR)
  IMPORT
  IMPLICIT NONE
  CLASS(*), INTENT(IN) :: BASE(*)
  INTEGER(KIND=MPI_ADDRESS_KIND), INTENT(IN) :: SIZE
  INTEGER, INTENT(IN) :: DISP_UNIT, INFO, COMM
  INTEGER, INTENT(OUT) :: WIN, IERROR
 END SUBROUTINE
 SUBROUTINE MPI_WIN_FENCE(ASSERT, WIN, IERROR)
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: ASSERT, WIN
  INTEGER, INTENT(OUT) :: IERROR
 END SUBROUTINE
 SUBROUTINE MPI_WIN_FREE(WIN, IERROR)
  IMPLICIT NONE
  INTEGER, INTENT(INOUT) :: WIN
  INTEGER, INTENT(OUT) :: IERROR
 END SUBROUTINE
 SUBROUTINE MPI_WIN_GET_GROUP(WIN, GROUP, IERROR)
  IMPLICIT NONE
  INTEGER WIN, GROUP, IERROR
 END SUBROUTINE
 SUBROUTINE MPI_WIN_LOCK(LOCK_TYPE, RANK, ASSERT, WIN, IERROR)
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: LOCK_TYPE, RANK, ASSERT, WIN
  INTEGER, INTENT(OUT) :: IERROR
 END SUBROUTINE
 SUBROUTINE MPI_WIN_POST(GROUP, ASSERT, WIN, IERROR)
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: GROUP, ASSERT, WIN
  INTEGER, INTENT(OUT) :: IERROR
 END SUBROUTINE
 SUBROUTINE MPI_WIN_START(GROUP, ASSERT, WIN, IERROR)
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: GROUP, ASSERT, WIN
  INTEGER, INTENT(OUT) :: IERROR
 END SUBROUTINE
 SUBROUTINE MPI_WIN_TEST(WIN, FLAG, IERROR)
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: WIN
  INTEGER, INTENT(OUT) :: IERROR
  LOGICAL, INTENT(OUT) :: FLAG
 END SUBROUTINE
 SUBROUTINE MPI_WIN_UNLOCK(RANK, WIN, IERROR)
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: RANK, WIN
  INTEGER, INTENT(OUT) :: IERROR
 END SUBROUTINE
 SUBROUTINE MPI_WIN_WAIT(WIN, IERROR)
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: WIN
  INTEGER, INTENT(OUT) :: IERROR
 END SUBROUTINE

! Extended Collective Operations

 SUBROUTINE MPI_EXSCAN(SENDBUF[PLURI], RECVBUF[PLURI], COUNT, DATATYPE, OP, COMM, IERROR)
  IMPLICIT NONE
  CLASS(*), INTENT(IN) :: SENDBUF(*)
  CLASS(*), INTENT(OUT) :: RECVBUF(*)
  INTEGER, INTENT(IN) :: COUNT, DATATYPE, OP, COMM
  INTEGER, INTENT(OUT) :: IERROR
 END SUBROUTINE

! External Interfaces

 SUBROUTINE MPI_COMM_CREATE_KEYVAL(COMM_COPY_ATTR_FN, COMM_DELETE_ATTR_FN, COMM_KEYVAL, EXTRA_STATE, &
                                   IERROR)
  IMPORT
  IMPLICIT NONE
  EXTERNAL COMM_COPY_ATTR_FN, COMM_DELETE_ATTR_FN
  INTEGER, INTENT(OUT) :: COMM_KEYVAL, IERROR
  INTEGER(KIND=MPI_ADDRESS_KIND), INTENT(IN) :: EXTRA_STATE
 END SUBROUTINE
 SUBROUTINE MPI_COMM_DELETE_ATTR(COMM, COMM_KEYVAL, IERROR)
  IMPLICIT NONE
  INTEGER, INTENT(INOUT) :: COMM
  INTEGER, INTENT(IN) :: COMM_KEYVAL
  INTEGER, INTENT(OUT) :: IERROR
 END SUBROUTINE
 SUBROUTINE MPI_COMM_FREE_KEYVAL(COMM_KEYVAL, IERROR)
  IMPLICIT NONE
  INTEGER, INTENT(INOUT) :: COMM_KEYVAL
  INTEGER, INTENT(OUT) :: IERROR
 END SUBROUTINE
 SUBROUTINE MPI_COMM_GET_ATTR(COMM, COMM_KEYVAL, ATTRIBUTE_VAL, FLAG, IERROR)
  IMPORT
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: COMM, COMM_KEYVAL
  INTEGER, INTENT(OUT) :: IERROR
  INTEGER(KIND=MPI_ADDRESS_KIND), INTENT(OUT) :: ATTRIBUTE_VAL
  LOGICAL, INTENT(OUT) :: FLAG
 END SUBROUTINE
 SUBROUTINE MPI_COMM_GET_NAME(COMM, COMM_NAME, RESULTLEN, IERROR)
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: COMM
  INTEGER, INTENT(OUT) :: RESULTLEN, IERROR
  CHARACTER*(*), INTENT(OUT) :: COMM_NAME
 END SUBROUTINE
 SUBROUTINE MPI_COMM_SET_ATTR(COMM, COMM_KEYVAL, ATTRIBUTE_VAL, IERROR)
  IMPORT
  IMPLICIT NONE
  INTEGER, INTENT(INOUT) :: COMM
  INTEGER, INTENT(IN) :: COMM_KEYVAL
  INTEGER, INTENT(OUT) :: IERROR
  INTEGER(KIND=MPI_ADDRESS_KIND), INTENT(IN) :: ATTRIBUTE_VAL
 END SUBROUTINE
 SUBROUTINE MPI_COMM_SET_NAME(COMM, COMM_NAME, IERROR)
  IMPLICIT NONE
  INTEGER, INTENT(INOUT) :: COMM
  INTEGER, INTENT(OUT) :: IERROR
  CHARACTER*(*), INTENT(IN) :: COMM_NAME
 END SUBROUTINE
 SUBROUTINE MPI_GREQUEST_COMPLETE(REQUEST, IERROR)
  IMPLICIT NONE
  INTEGER, INTENT(INOUT) :: REQUEST
  INTEGER, INTENT(OUT) :: IERROR
 END SUBROUTINE
 SUBROUTINE MPI_GREQUEST_START(QUERY_FN, FREE_FN, CANCEL_FN, EXTRA_STATE, REQUEST, IERROR)
  IMPORT
  IMPLICIT NONE
  INTEGER, INTENT(OUT) :: REQUEST, IERROR
  EXTERNAL QUERY_FN, FREE_FN, CANCEL_FN
  INTEGER (KIND=MPI_ADDRESS_KIND), INTENT(IN) :: EXTRA_STATE
 END SUBROUTINE
 SUBROUTINE MPI_INIT_THREAD(REQUIRED, PROVIDED, IERROR)
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: REQUIRED
  INTEGER, INTENT(OUT) :: PROVIDED, IERROR
 END SUBROUTINE
 SUBROUTINE MPI_IS_THREAD_MAIN(FLAG, IERROR)
  IMPLICIT NONE
  LOGICAL, INTENT(OUT) :: FLAG
  INTEGER, INTENT(OUT) :: IERROR
 END SUBROUTINE
 SUBROUTINE MPI_QUERY_THREAD(PROVIDED, IERROR)
  IMPLICIT NONE
  INTEGER, INTENT(OUT) :: PROVIDED, IERROR
 END SUBROUTINE
 SUBROUTINE MPI_STATUS_SET_CANCELLED(STATUS, FLAG, IERROR)
  IMPORT
  IMPLICIT NONE
  INTEGER, INTENT(INOUT) :: STATUS(MPI_STATUS_SIZE)
  INTEGER, INTENT(OUT) :: IERROR
  LOGICAL, INTENT(IN) :: FLAG
 END SUBROUTINE
 SUBROUTINE MPI_STATUS_SET_ELEMENTS(STATUS, DATATYPE, COUNT, IERROR)
  IMPORT
  IMPLICIT NONE
  INTEGER, INTENT(INOUT) :: STATUS(MPI_STATUS_SIZE)
  INTEGER, INTENT(IN) :: DATATYPE, COUNT
  INTEGER, INTENT(OUT) :: IERROR
 END SUBROUTINE
 SUBROUTINE MPI_TYPE_CREATE_KEYVAL(TYPE_COPY_ATTR_FN, TYPE_DELETE_ATTR_FN, TYPE_KEYVAL, EXTRA_STATE, &
                                   IERROR)
  IMPORT
  IMPLICIT NONE
  EXTERNAL TYPE_COPY_ATTR_FN, TYPE_DELETE_ATTR_FN
  INTEGER, INTENT(OUT) :: TYPE_KEYVAL, IERROR
  INTEGER(KIND=MPI_ADDRESS_KIND), INTENT(IN) :: EXTRA_STATE
 END SUBROUTINE
 SUBROUTINE MPI_TYPE_DELETE_ATTR(TYPE, TYPE_KEYVAL, IERROR)
  IMPLICIT NONE
  INTEGER, INTENT(INOUT) :: TYPE
  INTEGER, INTENT(IN) :: TYPE_KEYVAL
  INTEGER, INTENT(OUT) :: IERROR
 END SUBROUTINE
 SUBROUTINE MPI_TYPE_DUP(TYPE, NEWTYPE, IERROR)
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: TYPE
  INTEGER, INTENT(OUT) :: NEWTYPE, IERROR
 END SUBROUTINE
 SUBROUTINE MPI_TYPE_FREE_KEYVAL(TYPE_KEYVAL, IERROR)
  IMPLICIT NONE
  INTEGER, INTENT(INOUT) :: TYPE_KEYVAL
  INTEGER, INTENT(OUT) :: IERROR
 END SUBROUTINE
 SUBROUTINE MPI_TYPE_GET_ATTR(TYPE, TYPE_KEYVAL, ATTRIBUTE_VAL, FLAG, IERROR)
  IMPORT
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: TYPE, TYPE_KEYVAL
  INTEGER, INTENT(OUT) :: IERROR
  INTEGER(KIND=MPI_ADDRESS_KIND), INTENT(OUT) :: ATTRIBUTE_VAL
  LOGICAL, INTENT(OUT) :: FLAG
 END SUBROUTINE
 SUBROUTINE MPI_TYPE_GET_CONTENTS(DATATYPE, MAX_INTEGERS, MAX_ADDRESSES, MAX_DATATYPES, &
                                  ARRAY_OF_INTEGERS[PLURI], ARRAY_OF_ADDRESSES[PLURI], &
                                  ARRAY_OF_DATATYPES[PLURI], IERROR)
  IMPORT
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: DATATYPE, MAX_INTEGERS, MAX_ADDRESSES, MAX_DATATYPES
  INTEGER, INTENT(OUT) :: ARRAY_OF_INTEGERS(*), ARRAY_OF_DATATYPES(*), IERROR
  INTEGER(KIND=MPI_ADDRESS_KIND), INTENT(OUT) :: ARRAY_OF_ADDRESSES(*)
 END SUBROUTINE
 SUBROUTINE MPI_TYPE_GET_ENVELOPE(DATATYPE, NUM_INTEGERS, NUM_ADDRESSES, NUM_DATATYPES, COMBINER, IERROR)
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: DATATYPE
  INTEGER, INTENT(OUT) :: NUM_INTEGERS, NUM_ADDRESSES, NUM_DATATYPES, COMBINER, IERROR
 END SUBROUTINE
 SUBROUTINE MPI_TYPE_GET_NAME(TYPE, TYPE_NAME, RESULTLEN, IERROR)
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: TYPE
  INTEGER, INTENT(OUT) :: RESULTLEN, IERROR
  CHARACTER*(*), INTENT(OUT) :: TYPE_NAME
 END SUBROUTINE
 SUBROUTINE MPI_TYPE_SET_ATTR(TYPE, TYPE_KEYVAL, ATTRIBUTE_VAL, IERROR)
  IMPORT
  IMPLICIT NONE
  INTEGER, INTENT(INOUT) :: TYPE
  INTEGER, INTENT(IN) :: TYPE_KEYVAL
  INTEGER, INTENT(OUT) :: IERROR
  INTEGER(KIND=MPI_ADDRESS_KIND), INTENT(IN) :: ATTRIBUTE_VAL
 END SUBROUTINE
 SUBROUTINE MPI_TYPE_SET_NAME(TYPE, TYPE_NAME, IERROR)
  IMPLICIT NONE
  INTEGER, INTENT(INOUT) :: TYPE
  INTEGER, INTENT(OUT) :: IERROR
  CHARACTER*(*), INTENT(IN) :: TYPE_NAME
 END SUBROUTINE
 SUBROUTINE MPI_WIN_CREATE_KEYVAL(WIN_COPY_ATTR_FN, WIN_DELETE_ATTR_FN, WIN_KEYVAL, EXTRA_STATE, IERROR)
  IMPORT
  IMPLICIT NONE
  EXTERNAL WIN_COPY_ATTR_FN, WIN_DELETE_ATTR_FN
  INTEGER, INTENT(OUT) :: WIN_KEYVAL, IERROR
  INTEGER(KIND=MPI_ADDRESS_KIND), INTENT(IN) :: EXTRA_STATE
 END SUBROUTINE
 SUBROUTINE MPI_WIN_DELETE_ATTR(WIN, WIN_KEYVAL, IERROR)
  IMPLICIT NONE
  INTEGER, INTENT(INOUT) :: WIN
  INTEGER, INTENT(IN) :: WIN_KEYVAL
  INTEGER, INTENT(OUT) :: IERROR
 END SUBROUTINE
 SUBROUTINE MPI_WIN_FREE_KEYVAL(WIN_KEYVAL, IERROR)
  IMPLICIT NONE
  INTEGER, INTENT(INOUT) :: WIN_KEYVAL
  INTEGER, INTENT(OUT) :: IERROR
 END SUBROUTINE
 SUBROUTINE MPI_WIN_GET_ATTR(WIN, WIN_KEYVAL, ATTRIBUTE_VAL, FLAG, IERROR)
  IMPORT
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: WIN, WIN_KEYVAL
  INTEGER, INTENT(OUT) :: IERROR
  INTEGER(KIND=MPI_ADDRESS_KIND), INTENT(OUT) :: ATTRIBUTE_VAL
  LOGICAL, INTENT(OUT) :: FLAG
 END SUBROUTINE
 SUBROUTINE MPI_WIN_GET_NAME(WIN, WIN_NAME, RESULTLEN, IERROR)
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: WIN
  INTEGER, INTENT(OUT) :: RESULTLEN, IERROR
  CHARACTER*(*), INTENT(OUT) :: WIN_NAME
 END SUBROUTINE
 SUBROUTINE MPI_WIN_SET_ATTR(WIN, WIN_KEYVAL, ATTRIBUTE_VAL, IERROR)
  IMPORT
  IMPLICIT NONE
  INTEGER, INTENT(INOUT) :: WIN
  INTEGER, INTENT(IN) :: WIN_KEYVAL
  INTEGER, INTENT(OUT) :: IERROR
  INTEGER(KIND=MPI_ADDRESS_KIND), INTENT(IN) :: ATTRIBUTE_VAL
 END SUBROUTINE
 SUBROUTINE MPI_WIN_SET_NAME(WIN, WIN_NAME, IERROR)
  IMPLICIT NONE
  INTEGER, INTENT(INOUT) :: WIN
  INTEGER, INTENT(OUT) :: IERROR
  CHARACTER*(*), INTENT(IN) :: WIN_NAME
 END SUBROUTINE

! I/O

 SUBROUTINE MPI_FILE_CALL_ERRHANDLER(FH, ERRORCODE, IERROR)
  INTEGER, INTENT(IN) :: FH, ERRORCODE
  INTEGER, INTENT(OUT) :: IERROR
 END SUBROUTINE
 SUBROUTINE MPI_FILE_CLOSE(FH, IERROR)
  IMPLICIT NONE
  INTEGER, INTENT(INOUT) :: FH
  INTEGER, INTENT(OUT) :: IERROR
 END SUBROUTINE
 SUBROUTINE MPI_FILE_CREATE_ERRHANDLER(FUNCTION, ERRHANDLER, IERROR)
  IMPLICIT NONE
  EXTERNAL FUNCTION
  INTEGER, INTENT(OUT) :: ERRHANDLER, IERROR
 END SUBROUTINE
 SUBROUTINE MPI_FILE_DELETE(FILENAME, INFO, IERROR)
  IMPLICIT NONE
  CHARACTER*(*), INTENT(IN) :: FILENAME
  INTEGER, INTENT(IN) :: INFO
  INTEGER, INTENT(OUT) :: IERROR
 END SUBROUTINE
 SUBROUTINE MPI_FILE_GET_AMODE(FH, AMODE, IERROR)
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: FH
  INTEGER, INTENT(OUT) :: AMODE, IERROR
 END SUBROUTINE
 SUBROUTINE MPI_FILE_GET_ATOMICITY(FH, FLAG, IERROR)
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: FH
  INTEGER, INTENT(OUT) :: IERROR
  LOGICAL, INTENT(OUT) :: FLAG
 END SUBROUTINE
 SUBROUTINE MPI_FILE_GET_BYTE_OFFSET(FH, OFFSET, DISP, IERROR)
  IMPORT
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: FH
  INTEGER, INTENT(OUT) :: IERROR
  INTEGER(KIND=MPI_OFFSET_KIND), INTENT(IN) :: OFFSET
  INTEGER(KIND=MPI_OFFSET_KIND), INTENT(OUT) :: DISP
 END SUBROUTINE
 SUBROUTINE MPI_FILE_GET_ERRHANDLER(FILE, ERRHANDLER, IERROR)
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: FILE
  INTEGER, INTENT(OUT) :: ERRHANDLER, IERROR
 END SUBROUTINE
 SUBROUTINE MPI_FILE_GET_GROUP(FH, GROUP, IERROR)
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: FH
  INTEGER, INTENT(OUT) :: GROUP, IERROR
 END SUBROUTINE
 SUBROUTINE MPI_FILE_GET_INFO(FH, INFO_USED, IERROR)
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: FH
  INTEGER, INTENT(OUT) :: INFO_USED, IERROR
 END SUBROUTINE
 SUBROUTINE MPI_FILE_GET_POSITION(FH, OFFSET, IERROR)
  IMPORT
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: FH
  INTEGER, INTENT(OUT) :: IERROR
  INTEGER(KIND=MPI_OFFSET_KIND), INTENT(OUT) :: OFFSET
 END SUBROUTINE
 SUBROUTINE MPI_FILE_GET_POSITION_SHARED(FH, OFFSET, IERROR)
  IMPORT
  IMPLICIT NONE
  INTEGER, INTENT(INOUT) :: FH
  INTEGER, INTENT(OUT) :: IERROR
  INTEGER(KIND=MPI_OFFSET_KIND), INTENT(OUT) :: OFFSET
 END SUBROUTINE
 SUBROUTINE MPI_FILE_GET_SIZE(FH, SIZE, IERROR)
  IMPORT
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: FH
  INTEGER, INTENT(OUT) :: IERROR
  INTEGER(KIND=MPI_OFFSET_KIND), INTENT(OUT) :: SIZE
 END SUBROUTINE
 SUBROUTINE MPI_FILE_GET_TYPE_EXTENT(FH, DATATYPE, EXTENT, IERROR)
  IMPORT
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: FH, DATATYPE
  INTEGER, INTENT(OUT) :: IERROR
  INTEGER(KIND=MPI_ADDRESS_KIND), INTENT(OUT) :: EXTENT
 END SUBROUTINE
 SUBROUTINE MPI_FILE_GET_VIEW(FH, DISP, ETYPE, FILETYPE, DATAREP, IERROR)
  IMPORT
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: FH
  INTEGER, INTENT(OUT) :: ETYPE, FILETYPE, IERROR
  CHARACTER*(*), INTENT(OUT) :: DATAREP
  INTEGER(KIND=MPI_OFFSET_KIND), INTENT(IN) :: DISP
 END SUBROUTINE
 SUBROUTINE MPI_FILE_IREAD(FH, BUF[PLURI], COUNT, DATATYPE, REQUEST, IERROR)
  IMPLICIT NONE
  CLASS(*), INTENT(OUT) :: BUF(*)
  INTEGER, INTENT(INOUT) :: FH
  INTEGER, INTENT(IN) :: COUNT, DATATYPE
  INTEGER, INTENT(OUT) :: REQUEST, IERROR
 END SUBROUTINE
 SUBROUTINE MPI_FILE_IREAD_AT(FH, OFFSET, BUF[PLURI], COUNT, DATATYPE, REQUEST, IERROR)
  IMPORT
  IMPLICIT NONE
  CLASS(*), INTENT(OUT) :: BUF(*)
  INTEGER, INTENT(IN) :: FH, COUNT, DATATYPE
  INTEGER, INTENT(OUT) :: REQUEST, IERROR
  INTEGER(KIND=MPI_OFFSET_KIND), INTENT(IN) :: OFFSET
 END SUBROUTINE
 SUBROUTINE MPI_FILE_IREAD_SHARED(FH, BUF[PLURI], COUNT, DATATYPE, REQUEST, IERROR)
  IMPLICIT NONE
  CLASS(*), INTENT(IN) :: BUF(*)
  INTEGER, INTENT(INOUT) :: FH
  INTEGER, INTENT(IN) :: COUNT, DATATYPE
  INTEGER, INTENT(OUT) :: REQUEST, IERROR
 END SUBROUTINE
 SUBROUTINE MPI_FILE_IWRITE(FH, BUF[PLURI], COUNT, DATATYPE, REQUEST, IERROR)
  IMPORT
  IMPLICIT NONE
  CLASS(*), INTENT(IN) :: BUF(*)
  INTEGER, INTENT(INOUT) :: FH
  INTEGER, INTENT(IN) :: COUNT, DATATYPE
  INTEGER, INTENT(OUT) :: REQUEST, IERROR
 END SUBROUTINE
 SUBROUTINE MPI_FILE_IWRITE_AT(FH, OFFSET, BUF[PLURI], COUNT, DATATYPE, REQUEST, IERROR)
  IMPORT
  IMPLICIT NONE
  CLASS(*), INTENT(IN) :: BUF(*)
  INTEGER, INTENT(INOUT) :: FH
  INTEGER, INTENT(IN) :: COUNT, DATATYPE
  INTEGER, INTENT(OUT) :: REQUEST, IERROR
  INTEGER(KIND=MPI_OFFSET_KIND), INTENT(IN) :: OFFSET
 END SUBROUTINE
 SUBROUTINE MPI_FILE_IWRITE_SHARED(FH, BUF[PLURI], COUNT, DATATYPE, REQUEST, IERROR)
  IMPLICIT NONE
  CLASS(*), INTENT(IN) :: BUF(*)
  INTEGER, INTENT(INOUT) :: FH
  INTEGER, INTENT(IN) :: COUNT, DATATYPE
  INTEGER, INTENT(OUT) :: REQUEST, IERROR
 END SUBROUTINE
 SUBROUTINE MPI_FILE_OPEN(COMM, FILENAME, AMODE, INFO, FH, IERROR)
  IMPLICIT NONE
  CHARACTER*(*), INTENT(IN) :: FILENAME
  INTEGER, INTENT(IN) :: COMM, AMODE, INFO
  INTEGER, INTENT(OUT) :: FH, IERROR
 END SUBROUTINE
 SUBROUTINE MPI_FILE_PREALLOCATE(FH, SIZE, IERROR)
  IMPORT
  IMPLICIT NONE
  INTEGER, INTENT(INOUT) :: FH
  INTEGER, INTENT(OUT) :: IERROR
  INTEGER(KIND=MPI_OFFSET_KIND), INTENT(IN) :: SIZE
 END SUBROUTINE
 SUBROUTINE MPI_FILE_READ(FH, BUF[PLURI], COUNT, DATATYPE, STATUS, IERROR)
  IMPORT
  IMPLICIT NONE
  CLASS(*), INTENT(OUT) :: BUF(*)
  INTEGER, INTENT(INOUT) :: FH
  INTEGER, INTENT(IN) :: COUNT, DATATYPE
  INTEGER, INTENT(OUT) :: STATUS(MPI_STATUS_SIZE), IERROR
 END SUBROUTINE
 SUBROUTINE MPI_FILE_READ_ALL(FH, BUF[PLURI], COUNT, DATATYPE, STATUS, IERROR)
  IMPORT
  IMPLICIT NONE
  CLASS(*), INTENT(OUT) :: BUF(*)
  INTEGER, INTENT(INOUT) :: FH
  INTEGER, INTENT(IN) :: COUNT, DATATYPE
  INTEGER, INTENT(OUT) :: STATUS(MPI_STATUS_SIZE), IERROR
 END SUBROUTINE
 SUBROUTINE MPI_FILE_READ_ALL_BEGIN(FH, BUF[PLURI], COUNT, DATATYPE, IERROR)
  IMPLICIT NONE
  CLASS(*), INTENT(OUT) :: BUF(*)
  INTEGER, INTENT(INOUT) :: FH
  INTEGER, INTENT(IN) :: COUNT, DATATYPE
  INTEGER, INTENT(OUT) :: IERROR
 END SUBROUTINE
 SUBROUTINE MPI_FILE_READ_ALL_END(FH, BUF[PLURI], STATUS, IERROR)
  IMPORT
  IMPLICIT NONE
  CLASS(*), INTENT(OUT) :: BUF(*)
  INTEGER, INTENT(INOUT) :: FH
  INTEGER, INTENT(OUT) :: STATUS(MPI_STATUS_SIZE), IERROR
 END SUBROUTINE
 SUBROUTINE MPI_FILE_READ_AT(FH, OFFSET, BUF[PLURI], COUNT, DATATYPE, STATUS, IERROR)
  IMPORT
  IMPLICIT NONE
  CLASS(*), INTENT(OUT) :: BUF(*)
  INTEGER, INTENT(IN) :: FH, COUNT, DATATYPE
  INTEGER, INTENT(OUT) :: STATUS(MPI_STATUS_SIZE), IERROR
  INTEGER(KIND=MPI_OFFSET_KIND), INTENT(IN) :: OFFSET
 END SUBROUTINE
 SUBROUTINE MPI_FILE_READ_AT_ALL(FH, OFFSET, BUF[PLURI], COUNT, DATATYPE, STATUS, IERROR)
  IMPORT
  IMPLICIT NONE
  CLASS(*), INTENT(OUT) :: BUF(*)
  INTEGER, INTENT(IN) :: FH, COUNT, DATATYPE
  INTEGER, INTENT(OUT) :: STATUS(MPI_STATUS_SIZE), IERROR
  INTEGER(KIND=MPI_OFFSET_KIND), INTENT(IN) :: OFFSET
 END SUBROUTINE
 SUBROUTINE MPI_FILE_READ_AT_ALL_BEGIN(FH, OFFSET, BUF[PLURI], COUNT, DATATYPE, IERROR)
  IMPORT
  IMPLICIT NONE
  CLASS(*), INTENT(OUT) :: BUF(*)
  INTEGER, INTENT(IN) :: FH, COUNT, DATATYPE
  INTEGER, INTENT(OUT) :: IERROR
  INTEGER(KIND=MPI_OFFSET_KIND), INTENT(IN) :: OFFSET
 END SUBROUTINE
 SUBROUTINE MPI_FILE_READ_AT_ALL_END(FH, BUF[PLURI], STATUS, IERROR)
  IMPORT
  IMPLICIT NONE
  CLASS(*), INTENT(OUT) :: BUF(*)
  INTEGER, INTENT(IN) :: FH
  INTEGER, INTENT(OUT) :: STATUS(MPI_STATUS_SIZE), IERROR
 END SUBROUTINE
 SUBROUTINE MPI_FILE_READ_ORDERED(FH, BUF[PLURI], COUNT, DATATYPE, STATUS, IERROR)
  IMPORT
  IMPLICIT NONE
  CLASS(*), INTENT(OUT) :: BUF(*)
  INTEGER, INTENT(INOUT) :: FH
  INTEGER, INTENT(IN) :: COUNT, DATATYPE
  INTEGER, INTENT(OUT) :: STATUS(MPI_STATUS_SIZE), IERROR
 END SUBROUTINE
 SUBROUTINE MPI_FILE_READ_ORDERED_BEGIN(FH, BUF[PLURI], COUNT, DATATYPE, IERROR)
  IMPLICIT NONE
  CLASS(*), INTENT(OUT) :: BUF(*)
  INTEGER, INTENT(INOUT) :: FH
  INTEGER, INTENT(IN) :: COUNT, DATATYPE
  INTEGER, INTENT(OUT) :: IERROR
 END SUBROUTINE
 SUBROUTINE MPI_FILE_READ_ORDERED_END(FH, BUF[PLURI], STATUS, IERROR)
  IMPORT
  IMPLICIT NONE
  CLASS(*), INTENT(OUT) :: BUF(*)
  INTEGER, INTENT(INOUT) :: FH
  INTEGER, INTENT(OUT) :: STATUS(MPI_STATUS_SIZE), IERROR
 END SUBROUTINE
 SUBROUTINE MPI_FILE_READ_SHARED(FH, BUF[PLURI], COUNT, DATATYPE, STATUS, IERROR)
  IMPORT
  IMPLICIT NONE
  CLASS(*), INTENT(OUT) :: BUF(*)
  INTEGER, INTENT(INOUT) :: FH
  INTEGER, INTENT(IN) :: COUNT, DATATYPE
  INTEGER, INTENT(OUT) :: STATUS(MPI_STATUS_SIZE), IERROR
 END SUBROUTINE
 SUBROUTINE MPI_FILE_SEEK(FH, OFFSET, WHENCE, IERROR)
  IMPORT
  IMPLICIT NONE
  INTEGER, INTENT(INOUT) :: FH
  INTEGER, INTENT(IN) :: WHENCE
  INTEGER, INTENT(OUT) :: IERROR
  INTEGER(KIND=MPI_OFFSET_KIND), INTENT(IN) :: OFFSET
 END SUBROUTINE
 SUBROUTINE MPI_FILE_SEEK_SHARED(FH, OFFSET, WHENCE, IERROR)
  IMPORT
  IMPLICIT NONE
  INTEGER, INTENT(INOUT) :: FH
  INTEGER, INTENT(IN) :: WHENCE
  INTEGER, INTENT(OUT) :: IERROR
  INTEGER(KIND=MPI_OFFSET_KIND), INTENT(OUT) :: OFFSET
 END SUBROUTINE
 SUBROUTINE MPI_FILE_SET_ATOMICITY(FH, FLAG, IERROR)
  IMPLICIT NONE
  INTEGER, INTENT(INOUT) :: FH
  INTEGER, INTENT(OUT) :: IERROR
  LOGICAL, INTENT(IN) :: FLAG
 END SUBROUTINE
 SUBROUTINE MPI_FILE_SET_ERRHANDLER(FILE, ERRHANDLER, IERROR)
  IMPLICIT NONE
  INTEGER, INTENT(INOUT) :: FILE
  INTEGER, INTENT(IN) :: ERRHANDLER
  INTEGER, INTENT(OUT) :: IERROR
 END SUBROUTINE
 SUBROUTINE MPI_FILE_SET_INFO(FH, INFO, IERROR)
  IMPLICIT NONE
  INTEGER, INTENT(INOUT) :: FH
  INTEGER, INTENT(IN) :: INFO
  INTEGER, INTENT(OUT) :: IERROR
 END SUBROUTINE
 SUBROUTINE MPI_FILE_SET_SIZE(FH, SIZE, IERROR)
  IMPORT
  IMPLICIT NONE
  INTEGER, INTENT(INOUT) :: FH
  INTEGER, INTENT(OUT) :: IERROR
  INTEGER(KIND=MPI_OFFSET_KIND), INTENT(IN) :: SIZE
 END SUBROUTINE
 SUBROUTINE MPI_FILE_SET_VIEW(FH, DISP, ETYPE, FILETYPE, DATAREP, INFO, IERROR)
  IMPORT
  IMPLICIT NONE
  INTEGER, INTENT(INOUT) :: FH
  INTEGER, INTENT(IN) :: ETYPE, FILETYPE, INFO
  INTEGER, INTENT(OUT) :: IERROR
  CHARACTER*(*), INTENT(IN) :: DATAREP
  INTEGER(KIND=MPI_OFFSET_KIND), INTENT(IN) :: DISP
 END SUBROUTINE
 SUBROUTINE MPI_FILE_SYNC(FH, IERROR)
  IMPLICIT NONE
  INTEGER, INTENT(INOUT) :: FH
  INTEGER, INTENT(OUT) :: IERROR
 END SUBROUTINE
 SUBROUTINE MPI_FILE_WRITE(FH, BUF[PLURI], COUNT, DATATYPE, STATUS, IERROR)
  IMPORT
  IMPLICIT NONE
  CLASS(*), INTENT(IN) :: BUF(*)
  INTEGER, INTENT(INOUT) :: FH
  INTEGER, INTENT(IN) :: COUNT, DATATYPE
  INTEGER, INTENT(OUT) :: STATUS(MPI_STATUS_SIZE), IERROR
 END SUBROUTINE
 SUBROUTINE MPI_FILE_WRITE_ALL(FH, BUF[PLURI], COUNT, DATATYPE, STATUS, IERROR)
  IMPORT
  IMPLICIT NONE
  CLASS(*), INTENT(IN) :: BUF(*)
  INTEGER, INTENT(INOUT) :: FH
  INTEGER, INTENT(IN) :: COUNT, DATATYPE
  INTEGER, INTENT(OUT) :: STATUS(MPI_STATUS_SIZE), IERROR
 END SUBROUTINE
 SUBROUTINE MPI_FILE_WRITE_ALL_BEGIN(FH, BUF[PLURI], COUNT, DATATYPE, IERROR)
  IMPLICIT NONE
  CLASS(*), INTENT(IN) :: BUF(*)
  INTEGER, INTENT(INOUT) :: FH
  INTEGER, INTENT(IN) :: COUNT, DATATYPE
  INTEGER, INTENT(OUT) :: IERROR
 END SUBROUTINE
 SUBROUTINE MPI_FILE_WRITE_ALL_END(FH, BUF[PLURI], STATUS, IERROR)
  IMPORT
  IMPLICIT NONE
  CLASS(*), INTENT(IN) :: BUF(*)
  INTEGER, INTENT(INOUT) :: FH
  INTEGER, INTENT(OUT) :: STATUS(MPI_STATUS_SIZE), IERROR
 END SUBROUTINE
 SUBROUTINE MPI_FILE_WRITE_AT(FH, OFFSET, BUF[PLURI], COUNT, DATATYPE, STATUS, IERROR)
  IMPORT
  IMPLICIT NONE
  CLASS(*), INTENT(IN) :: BUF(*)
  INTEGER, INTENT(INOUT) :: FH
  INTEGER, INTENT(IN) :: COUNT, DATATYPE
  INTEGER, INTENT(OUT) :: STATUS(MPI_STATUS_SIZE), IERROR
  INTEGER(KIND=MPI_OFFSET_KIND), INTENT(IN) :: OFFSET
 END SUBROUTINE
 SUBROUTINE MPI_FILE_WRITE_AT_ALL(FH, OFFSET, BUF[PLURI], COUNT, DATATYPE, STATUS, IERROR)
  IMPORT
  IMPLICIT NONE
  CLASS(*), INTENT(IN) :: BUF(*)
  INTEGER, INTENT(INOUT) :: FH
  INTEGER, INTENT(IN) :: COUNT, DATATYPE
  INTEGER, INTENT(OUT) :: STATUS(MPI_STATUS_SIZE), IERROR
  INTEGER(KIND=MPI_OFFSET_KIND), INTENT(IN) :: OFFSET
 END SUBROUTINE
 SUBROUTINE MPI_FILE_WRITE_AT_ALL_BEGIN(FH, OFFSET, BUF[PLURI], COUNT, DATATYPE, IERROR)
  IMPORT
  IMPLICIT NONE
  CLASS(*), INTENT(IN) :: BUF(*)
  INTEGER, INTENT(INOUT) :: FH
  INTEGER, INTENT(IN) :: COUNT, DATATYPE
  INTEGER, INTENT(OUT) :: IERROR
  INTEGER(KIND=MPI_OFFSET_KIND) OFFSET
 END SUBROUTINE
 SUBROUTINE MPI_FILE_WRITE_AT_ALL_END(FH, BUF[PLURI], STATUS, IERROR)
  IMPORT
  IMPLICIT NONE
  CLASS(*), INTENT(IN) :: BUF(*)
  INTEGER, INTENT(INOUT) :: FH
  INTEGER, INTENT(OUT) :: STATUS(MPI_STATUS_SIZE), IERROR
 END SUBROUTINE
 SUBROUTINE MPI_FILE_WRITE_ORDERED(FH, BUF[PLURI], COUNT, DATATYPE, STATUS, IERROR)
  IMPORT
  IMPLICIT NONE
  CLASS(*), INTENT(IN) :: BUF(*)
  INTEGER, INTENT(INOUT) :: FH
  INTEGER, INTENT(IN) :: COUNT, DATATYPE
  INTEGER, INTENT(OUT) :: STATUS(MPI_STATUS_SIZE), IERROR
 END SUBROUTINE
 SUBROUTINE MPI_FILE_WRITE_ORDERED_BEGIN(FH, BUF[PLURI], COUNT, DATATYPE, IERROR)
  IMPLICIT NONE
  CLASS(*), INTENT(IN) :: BUF(*)
  INTEGER, INTENT(INOUT) :: FH
  INTEGER, INTENT(IN) :: COUNT, DATATYPE
  INTEGER, INTENT(OUT) :: IERROR
 END SUBROUTINE
 SUBROUTINE MPI_FILE_WRITE_ORDERED_END(FH, BUF[PLURI], STATUS, IERROR)
  IMPORT
  IMPLICIT NONE
  CLASS(*), INTENT(IN) :: BUF(*)
  INTEGER, INTENT(INOUT) :: FH
  INTEGER, INTENT(OUT) :: STATUS(MPI_STATUS_SIZE), IERROR
 END SUBROUTINE
 SUBROUTINE MPI_FILE_WRITE_SHARED(FH, BUF[PLURI], COUNT, DATATYPE, STATUS, IERROR)
  IMPORT
  IMPLICIT NONE
  CLASS(*), INTENT(IN) :: BUF(*)
  INTEGER, INTENT(INOUT) :: FH
  INTEGER, INTENT(IN) :: COUNT, DATATYPE
  INTEGER, INTENT(OUT) :: STATUS(MPI_STATUS_SIZE), IERROR
 END SUBROUTINE
 SUBROUTINE MPI_REGISTER_DATAREP(DATAREP, READ_CONVERSION_FN, WRITE_CONVERSION_FN, DTYPE_FILE_EXTENT_FN,&
                                 EXTRA_STATE, IERROR)
  IMPORT
  IMPLICIT NONE
  CHARACTER*(*), INTENT(IN) :: DATAREP
  EXTERNAL READ_CONVERSION_FN, WRITE_CONVERSION_FN, DTYPE_FILE_EXTENT_FN
  INTEGER(KIND=MPI_ADDRESS_KIND), INTENT(IN) :: EXTRA_STATE
  INTEGER, INTENT(OUT) :: IERROR
 END SUBROUTINE

! Language Bindings

 SUBROUTINE MPI_SIZEOF(X[PLURI], SIZE, IERROR)
  IMPLICIT NONE
  CLASS(*) :: X
  INTEGER, INTENT(OUT) :: SIZE, IERROR
 END SUBROUTINE
 SUBROUTINE MPI_TYPE_CREATE_F90_COMPLEX(P, R, NEWTYPE, IERROR)
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: P, R
  INTEGER, INTENT(OUT) :: NEWTYPE, IERROR
 END SUBROUTINE
 SUBROUTINE MPI_TYPE_CREATE_F90_INTEGER(R, NEWTYPE, IERROR)
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: R
  INTEGER, INTENT(OUT) :: NEWTYPE, IERROR
 END SUBROUTINE
 SUBROUTINE MPI_TYPE_CREATE_F90_REAL(P, R, NEWTYPE, IERROR)
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: P, R
  INTEGER, INTENT(OUT) :: NEWTYPE, IERROR
 END SUBROUTINE
 SUBROUTINE MPI_TYPE_MATCH_SIZE(TYPECLASS, SIZE, TYPE, IERROR)
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: TYPECLASS, SIZE
  INTEGER, INTENT(OUT) :: TYPE, IERROR
 END SUBROUTINE

end interface
end module